### ISSUE TITLE
Consider using grass for sass

### ISSUE THREAD

**Issue by svenstaro** [getzola/zola#1083]
Currently, zola is using sass-rs which needs a C library which makes cross-compilation a pain. I suggest considering using [grass](https://github.com/connorskees/grass) which is a pure Rust implementation of sass. It _might_ not be ready yet but if you think it's too early then let this be a tracking issue. Perhaps it can be offered as an alternative option? Zola already has alternatives in for linkfetching with rustls vs openssl so perhaps this could be another one of those options?

This is related to #1001.

**Comment by Keats** [comment]
I've been keeping an eye on it for a while. I'll switch it once the author thinks it's ready.

**Comment by michalfita** [comment]
So far [grass](https://github.com/connorskees/grass)'s numbers of official tests passed looks better than [rsass](https://github.com/kaj/rsass)'s (that's BTW demonstration of negative side of open source where two project with the same purpose pull in different direction instead of join forces to speed up development).

I'm really waiting for a day when Zola switches to Rust-native SASS and let me install itself by just `cargo install zola`.

**Comment by Keats** [comment]
> cargo install zola

That's not going to happen, until they allow dev-only workspaces. I don't want to have to upload `n` zola-* crates there only to make compilation speed tolerable.

I'm checking `grass` every week, I want to drop libsass too!

**Comment by blfpd** [comment]
- 2020-10-26 [Sass blog:  LibSass is Deprecated ](https://sass-lang.com/blog/libsass-is-deprecated)
- Starting from [`grass`](https://github.com/connorskees/grass/releases) v0.9.4, it is possible to compile Twitter Bootstrap 4 as well as bulma-scss.

I think it could be nice to have it for the milestone `0.14` as a feature flag (opt in or out). Wdyt?

**Comment by Keats** [comment]
https://github.com/connorskees/grass/issues/19#issuecomment-739529408

**Comment by Keats** [comment]
Closing as duplicate of https://github.com/getzola/zola/issues/1535 which has more comments.
