### ISSUE TITLE
Documentation use with Github Pages is outdated

### ISSUE THREAD

**Issue by jjbarr** [getzola/zola#1117]
At present, the documentation for using Zola with GitHub Pages is outdated, and using it as it currently stands will result in confusing, unexpected behavior. Most notably, Zola will not successfully run at all in the default Travis environment: you need to add `dist: bionic` to the top of the file to get a newer Ubuntu (and a newer version of libssl, which is the actual issue). 

Additionally, if the user does not change the link provided for downloading Zola, they will end up with 0.9.0 in travis. This will cause confusing issues: RSS and Atom feeds won't be generated correctly, as the configuration option for doing so has changed since 0.9.0's release. This technically isn't a bug, as the documentation explicitly states to update the link to the version you want, but it's probably a good idea to have a reasonable default.

## Proposed solution
Update the current example `.travis.yml` so that it will actually run successfully and build a site, and doesn't have versioning pitfalls lying in wait.

**Comment by schoenenberg** [comment]
@jjbarr I suggest adding a description for _GitHub Actions_ as well. I prefer to have everything integrated into one tool instead of multiple tools.

In the theme [zola-paper](https://github.com/schoenenberg/zola-paper) (see action: [main.yml](https://github.com/schoenenberg/zola-paper/blob/master/.github/workflows/main.yml)) I already implemented it with GitHub Actions. Also had a discussion with @reisub0 about the token see [here](https://github.com/reisub0/zola-paper/commit/6dbad68783ede4f892fdc8d4e25397e90ab054fa).

**Comment by therealprof** [comment]
I also have it integrated with GH actions, you can check it out here and steal whatever you like: https://github.com/therealprof/therealprof.github.io/blob/code/.github/workflows/zola.yml

**Comment by Keats** [comment]
It would be nice if someone could a PR to update the docs. I would recommend using GH action in the new docs rather than Travis too.

**Comment by schoenenberg** [comment]
Starting work on it.

**Comment by Keats** [comment]
Thanks @schoenenberg !
