### ISSUE TITLE
Use platform specific path separators 

### ISSUE THREAD

**Issue by Lucretiel** [getzola/zola#1140]
https://github.com/getzola/zola/blob/d198ad64dbcdb781b946991055ed8f591cadfba9/components/library/src/content/file_info.rs#L62-L66

We should prefer using the functionality in `std::Path` to construct new path strings, to ensure it's always portable across platforms.

**Comment by Keats** [comment]
In that case probably not. This is exposed to the templates so we want a single representing to the end user. It would suck if I do something like `{% if page.relative_path == "something/other.md" %}` and someone on Windows was not able to build the site because it would now be `something\other.md`. Changing the template to that will now make the site unbuildable for users on OSX/Linux.
That's the reason for not using platform specific separators on exposed paths. We do keep `Path` and `PathBuf` internally though.
