### ISSUE TITLE
Need examples of code using each named highlight scheme

### ISSUE THREAD

**Issue by tbrowder** [getzola/zola#1197]
# Documentation issue

There is a long list of named highlight schemes but the links for some of them don't seem to work. In particular, the following cannot be seen:

+ base16-ocean-light
+ base16-ocean-dark

**Comment by Keats** [comment]
Looks like the site is not working with spaces in names anymore? It definitely used to :/ and it doesn't seem maintained anymore...

**Comment by rootkea** [comment]
It's been almost 5 years now since upstream has removed `base16-ocean-light` and `base16-ocean-dark` themes. https://github.com/chriskempson/base16-textmate/commit/d5e178c2780c36bc62bf34db9131df092bfc0d27

There have been `base16-ocean` and `base16-oceanicnext` along with other base16-textmate themes though. See https://github.com/chriskempson/base16-textmate/tree/master/Themes

We should remove these 2 defunct themes and also select some other upstream-supported theme instead of `highlight_theme = "base16-ocean-dark"` in config.toml docs https://www.getzola.org/documentation/getting-started/configuration/

**Comment by Keats** [comment]
When https://github.com/getzola/zola/pull/1242 is merged in it should be easy to build a page to preview them.
Let's update those themes

**Comment by rootkea** [comment]
Does Zola support Sublime Text 3 themes too? Or just v2 themes? v2 themes were in xml format while v3 themes are in json format so may be not?

In that case this sentence needs to be updated on https://www.getzola.org/documentation/getting-started/configuration/

> Zola uses the Sublime Text themes, making it very easy to add more.

I'm following up on the current list and found that some themes have moved to v3 format and have removed the v2 ones from upstream.

**Comment by Keats** [comment]
It should work for both but I'm not 100% sure

**Comment by rootkea** [comment]
So how should I check that?

I think I need to:
1. drop v3 theme file in sublime/themes directory
2. How to add to binary file `all.themedump`?
3. cargo build
4. use freshly built zola binary e..g `zola serve`

Is that correct? I'm not sure how to go about step 2 though...

**Comment by Keats** [comment]
See https://github.com/getzola/zola/blob/master/CONTRIBUTING.md#adding-a-theme for step 2

**Comment by rootkea** [comment]
Oops! Sorry, I should have read the CONTRIBUTING.md. Thanks!

**Comment by rootkea** [comment]
`generate_sublime` didn't add v3 theme files to `all.themedump`. So I guess Zola supports only Sublime Text 2 themes and not v3 themes.

1. Is there a plan to support Sublime Text 3 themes too?
2. If not then shouldn't we remove highlight themes which have removed v2 files upstream and now only provide v3 files?
 a. from the doc https://www.getzola.org/documentation/getting-started/configuration/
 b. from `sublime/themes` - (not sure about this as removing theme file from this dir can lead to next version of zola breaking someone's site)

**Comment by rootkea** [comment]
To be sure let me try some another v3 theme file...

Edit - Nope, v3 themes don't work with Zola.

**Comment by rootkea** [comment]
So there are total 41 highlight themes on https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting but 42 in `sublime/themes` (https://github.com/getzola/zola/blob/master/sublime/themes/green.tmTheme is in `sublime/themes` dir but has no mention in docs. Edit - this should be fixed by #1482)

Out of these 41 documented themes following 8 themes have removed Sublime Text 2 theme files upstream:
1. base16-ocean-dark
2. base16-ocean-light
3. ayu-dark
4. ayu-light
5. ayu-mirage
6. kronuz
7. solarized-dark
8. solarized-light

This is why none of these 8 themes work on https://tmtheme-editor.herokuapp.com as upstream links return 404.

These other 3 Sublime Text themes were never there at upstream. They have been directly added in Zola:
1. gruvbox-dark
2. gruvbox-light
3. nyx-bold

And this 1 theme has Sublime Text 2 theme file upstream but the repo has been archived:
1. one-dark

**Comment by rootkea** [comment]
BTW, I don't understand this design of highlight themes.

1. Why to add highlight themes in zola binary?
2. Why not follow Zola Themes approach where user simply provides a theme name via `theme` variable and it's the responsibility of user to clone the said theme.

Zola Themes approach saves us from themes being removed upstream or other issues as it's the responsibility of user to get the theme. Bundling theme with binary itself now makes us a party to share the burden if upstream has removed the said theme file (or dropped support).

**Comment by rootkea** [comment]
Also on https://www.getzola.org/documentation/getting-started/configuration/ `highlight_theme` variable should be left unassigned just like `theme` variable as we don't control the theme upstream.

Like how in this particular case `highlight_theme` is set to `base16-ocean-dark` whose upstream has dropped Sublime Text 2 theme file for almost 5 years now.

Also, we will be saving ourselves from dictating/recommending any one highlight theme.

Edit - Opened #1482 for the same

**Comment by Keats** [comment]
Closing the original issue, not going to add examples for each.
