### ISSUE TITLE
Offset for Headings

### ISSUE THREAD

**Issue by vbrandl** [getzola/zola#1330]
When generating HTML from markdown content, `# Heading1` gets rendered as a `<h1>`, `## Heading2` gets rendered as a `<h2>` and so on, as expected.

Depending on the template and structuring of a page, I often use `h1` and `h2` for the title and description of the page itself and I'd like to render `# Heading1` as a `h3`.

Is it possible to define an offset `o` (in this case `2`) and when transforming the markdown to HTML, every heading will be converted to `number of # + o`?

**Comment by Keats** [comment]
It isn't possible and I don't think I would add that feature to Zola. I do the offset manually in my own site https://raw.githubusercontent.com/Keats/vincentprouillet/master/content/blog/2013-09-02_testing-django-projects.md

**Comment by xpe** [comment]
@Keats You wrote "It isn't possible" in 2021. But what do you mean? If you mean "it isn't possible at present with our choice of dependencies" then I _might_ agree -- or I might have agreed given the state of things in 2021.

But of course it **is** possible to adjust a markdown processor apply offsets to headings; e.g. map `#` -> `<h3>` and `##` -> `<h4>` and so on.

For what it is worth, this idea is requested many times across many different projects. It isn't a rare thing; the idea is "in the air". It has been implemented in at least one markdown processor; for example, see [BlackFriday][1] a popular Markdown processor for GoLang:

```go
// HTMLRendererParameters is a collection of supplementary parameters tweaking
// the behavior of various parts of HTML renderer.
type HTMLRendererParameters struct {
	// ... <content snipped by xpe> ...      
	// Increase heading levels: if the offset is 1, <h1> becomes <h2> etc.
	// Negative offset is also valid.
	// Resulting levels are clipped between 1 and 6.
	HeadingLevelOffset int
}
```

Background: I'm a big proponent of being as clear and transparent as possible... this might be _difficult_  -- or perceived as not _important_ because there are easy _workarounds_, but it is _possible_. Being very blunt in this way about the truth will allow other people to build on the knowledge, at least, even if your decision as maintainer is to not take the project in that direction.

[1]: https://github.com/russross/blackfriday/blob/v2.0.1/html.go#L91-L94

**Comment by xpe** [comment]
It is also worth mentioning that the _manual_ workaround mentioned above doesn't work if the Markdown gets included by different templates which use different nesting levels for headers.

**Comment by xpe** [comment]
There is also some ongoing confusion about what is considered to be best practices around `<h1>`, `<h2>` relative to elements like `<section>` or `<article>`. I'm not an expert on this debate, but I defer to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements :

> Avoid using multiple `<h1>` elements on one page
>
> While using multiple `<h1>` elements on one page is allowed by the HTML standard (as long as they are not [nested](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#nesting)), this is not considered a best practice. A page should generally have a single `<h1>` element that describes the content of the page (similar to the document's `<title>` element).
>
> Note: Nesting multiple `<h1>` elements in nested [sectioning elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#content_sectioning) was allowed in older versions of the HTML standard. However, this was never considered a best practice and is now non-conforming. Read more in [There Is No Document Outline Algorithm](https://adrianroselli.com/2016/08/there-is-no-document-outline-algorithm.html).

**Comment by xpe** [comment]
I requested this feature with Zola's Markdown processor, `pulldown-cmark`: https://github.com/pulldown-cmark/pulldown-cmark/issues/888

**Comment by Keats** [comment]
I don't mind adding the option in Zola if it's added in pulldown_cmark, but I wouldn't implement it in Zola

**Comment by xpe** [comment]
@Keats You seem so _certain_ that you wouldn't. Is there a rationale for this? Is there a logic that drives your decision?

See also: https://github.com/pulldown-cmark/pulldown-cmark/issues/888#issuecomment-2114864203

**Comment by Keats** [comment]
Just trying to avoid adding too many markdown changes in Zola as well as having dozens of config options
