### ISSUE TITLE
Incorrect HTML generated for shortcode inside `<div>`

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1500]
Hello!

This is my shortcode template:
```
$ cat templates/shortcodes/google.html 
<div>
<a href="https://google.com/search?q={{query}}">Google Search</a>
</div>
$
```

This is how I invoke the shortcode:
```
foo {{ google(query="apple") }} bar.
````

And this is what I get:
```
  <p>foo <div>
<a href="https://google.com/search?q=apple">Google Search</a></p>
</div> bar.
```

I expected `</p>` after `bar.`

**Comment by rootkea** [comment]
Also I don't understand this from shortcode docs:
> The Markdown renderer will wrap an inline HTML node such as `<a>` or `<span>` into a paragraph. If you want to disable this behaviour, wrap your shortcode in a `<div>`.

But the markdown renderer does not wrap `<a>` into paragraph.

e.g.
This is my shortcode template:
```
$ cat templates/shortcodes/google.html 
<a href="https://google.com/search?q={{query}}">Google Search</a>
$
```

This is how I invoke shortcode:
```
{{ google(query="apple") }}
```

And this is the HTML generated:
```
<a href="https://google.com/search?q=apple">Google Search</a>
```

No `<p>` so I don't understand the point of wrapping shortcode inside `<div>`

**Comment by Keats** [comment]
I believe it's referring to the shortcodes with `{% %}`

**Comment by rootkea** [comment]
Umm.. I modified the above shortcode to use `{% %}` but still no `<p>`
```
$ cat templates/shortcodes/google.html 
<a href="https://google.com/search?q={% if query %}{{query}}{% endif %}">Google Search</a>
$
```
What am I missing?

Edit - I even tried encompassing whole shortcode inside `{% if query %}` and `{% endif %}` but still no `<p>`.

**Comment by coastalwhite** [comment]
Can confirm some weird behavior. Will do some more investigation, hopefully tomorrow.

From what I found now, this is a bug that happens when you have a shortcode surrounded by a div on the same line as some other text. While testing I found some even weirder possibly more problematic stuff.

So using the following shortcode:

*shortcodes/txt.html*
```html
<div>
     Some text
</div>
```

Here are some extremely strange outputs.

> *Note:* Sorry for the hard to read format.

# Test 1
## Input
```
{{ txt() }}
```

## Output
```html
<div>
    Some text
</div>
```

## Conclusion
As expected.

# Test 2
## Input
```
foo
{{ txt() }}
```

## Output
```html
<p>foo</p>
<div>
    Some text
</div>
```

## Conclusion
Not as expected, I think? Not 100% sure. I would imagine it would still create a `<p>` tag around both of them?

# Test 3
## Input
```
foo {{ txt() }}
```

## Output
```html
<p>foo <div>
    Some text</p>
</div>
```

## Conclusion
**Not** as expected.

# Test 4
## Input
```
{{ txt() }}{{ txt() }}
```

## Output
```html
<div>
    Some text
</div><pre data-shortcode><div>
<pre style="background-color:#eff1f5;color:#4f5b66;"><code><span>Some text
</span></code></pre>
</div></pre>
```
## Conclusion
What? Most definitely **not** as expected. The coloring is probably theme or code-highlight dependent (not tested).


# Test 5
## Input
```
{{ txt() }}
{{ txt() }}
```

## Output
```html
<div>
    Some text
</div>
<div>
    Some text
</div>
```

## Conclusion
As expected, I think?

# Hypothesis
There is some intermediate step which introduces some characters somewhere. These might be wrongfully interpreted when applying shortcodes, especially for the second time, since seemingly random `<pre>` tags show up. There is also some weird behavior with paragraphs which do or don't go around shortcodes.

**Comment by Keats** [comment]
The whole shortcode pass needs to be rewritten from scratch it has lots of weird cases like that.
Some shortcodes are wrapped in `<pre>` to ensure the Markdown parser doesn't process them further but it's not very consistent as you can see

**Comment by coastalwhite** [comment]
I will have a look what can be done to make it more stable.

As for this specific issue. The issue only occurs for multiline shortcodes, so a very short-term fix may be to remove whitespace or line-breaks in shortcodes.

**Comment by Keats** [comment]
> The issue only occurs for multiline shortcodes, so a very short-term fix may be to remove whitespace or line-breaks in shortcodes.

That would break some shortcodes :/ It's a very tricky balancing exercise

**Comment by TimotheosFirestone** [comment]
I agree with fixing this as a priority. I have experienced bugs that make it very difficult to create a functioning website, because the whole page layout becomes invalid HTML due to mismatching tags.

If my Markdown is 

```
- support the native biodiversity, forest cover, and ecologically-sustainable productive capacity of all property managed or owned; {{ annotate(body="is 'for all property managed or owned' part of the mission, or is that better under strategy?") }}
- et cetera
```

and my shortcode `annotate.html` is

```
<!-- start --><div class="annotate{% if class %} {{class}}{% endif %}">
	{% if body %}<div>{{ body }}</div>{% endif %}
</div><!-- end -->
```

then the result comes out interlaced / mangled, like this:

```
<ul>
<li>support the native biodiversity, forest cover, and ecologically-sustainable productive capacity of all property managed or owned; <!-- start --><div class="annotate">  <div>is &#x27;for all property managed or owned&#x27; part of the mission, or is that better under strategy?</div>
</li>
</ul>
</div><!-- end -->
<ul>
<li>
<p>et cetera</p>
</li>
</ul>
```

which destroys the whole page layout (!) because of mismatched tags.

Note that it seems to create a new `<ul>` list for the next bullet point, as well. 

If I use the same `annotate.html` shortcode and my Markdown is the same but with a newline:

```
- support the native biodiversity, forest cover, and ecologically-sustainable productive capacity of all property managed or owned;
{{ annotate(body="is 'for all property managed or owned' part of the mission, or is that better under strategy?") }}

- et cetera
```

it renders "better" (doesn't break the whole page) but the content is no longer in the desired `<li>` at all, and it still "breaks out of" the parent `<ul>` like this (making two separate `</ul>`s, undesired):

```
<ul>
<li>support the native biodiversity, forest cover, and ecologically-sustainable productive capacity of all property managed or owned;</li>
</ul>
<!-- start --><div class="annotate">
	<div>is &#x27;for all property managed or owned&#x27; part of the mission, or is that better under strategy?</div>
	
</div><!-- end -->
<ul>
<li>
<p>et cetera</p>
</li>
</ul>
```

I just thought that I'd comment so that the `<ul><li>` cases are also considered in fixing this issue and #1564 :)

**Comment by chris-morgan** [comment]
I just got to this point in upgrading my fork from ~0.10.2, it slightly broke my tty-player shortcode as used in https://chrismorgan.info/blog/make-and-git-diff-test-harness/, inserting a spurious second `</pre>` after the `</tty-player>`. Attempts at fixing this produced various bizarre effects including moving the `</pre>` instead of duplicating it, introducing completely new and unrelated `<pre><code>`, spurious paragraphs and the likes. But to be clear, it worked perfectly at 0.10.2; I’m guessing shortcode-related changes in 0.12.0 or 0.12.1 broke things.

Then I tried renaming the shortcode template from .html to .md (new functionality in 0.12.0), and it fixed this particular issue completely.

I haven’t dug any deeper to remind myself of how exactly .html shortcodes used to work or to find out exactly how .html or .md shortcodes are working now, but this may be a suitable workaround for at least some cases.

As I’ve always said, Markdown is not designed for principled extension and it’s quite impossible for shortcodes to do the “right” thing in all cases, because Markdown doesn’t have a sane processing model that would allow semantic substitution, and textual substitution will get things wrong. It’s a matter of choosing which models to support and what workarounds to suggest for the things that model mangles.

(Pro tip: when upgrading Zola, build your site with the old version and the new version and diff the two (e.g. `git diff --no-index public-old public`), potentially with some normalisation to filter out noise from the diffs when you recognise acceptable differences that keep on coming up, e.g. for comparing the old timestamp cachebusting with hash cachebusting, something like `find public -type f -print0 | xargs -0 sed -i 's/\?[th]=[0-9a-f]\+/?CACHEBUST/`. This is very useful for handling breaking changes in Zola and making sure you get the required changes right, and for finding bugs like this.)

**Comment by coastalwhite** [comment]
This should all be handled in #1564, since the new structure for parsing and handling the shortcodes also removes this weird double parsing (which causes the issues most people are having). Sadly, because I am currently moving and my laptop really struggles to compile the codebase, it is difficult for me to make a lot of progress. At the start of september, I should have full access to a more powerful pc again. At which point working on this bug and the general issue should be a lot easier. This is not to say I won't look at it till then, just that productivity is low till then.
