### ISSUE TITLE
base_url breaks the layout rendering

### ISSUE THREAD

**Issue by NuLL3rr0r** [getzola/zola#180]
I noticed if I enter a base_url similar to this in config.toml it breaks the layout in the generated site:

    base_url = "https://example.com"

But, this one is fine:

    base_url = "https://example.com/"

It took me an hour to figure out cause of the error.

Steps to reproduce on both v0.2.2 and master branch:

1. git clone git@gitlab.com:Keats/vincent.is.git

2. Modify config.toml and replace
```
    base_url = "https://vincent.is/"
```
with
```
    base_url = "https://vincent.is"
```

3. Run

```
$ gutenberg serve --interface 0.0.0.0 --port 2000
```

4. Browse http://127.0.0.1:2000/

**Comment by Keats** [comment]
That's because I didn't update my site yet to use https://www.getgutenberg.io/documentation/templates/overview/#get-url so the links in my `<head>` for CSS and rss are only valid when `base_url = "https://vincent.is"`

If you use the global function linked above to create URLs, it will handle trailing slash automatically

**Comment by Keats** [comment]
Updated my site: https://gitlab.com/Keats/vincent.is/commit/3aab7b2a6b75477367dcb04cc3545409280c7ef9

You can try with both base_url now and it should work in both cases

**Comment by NuLL3rr0r** [comment]
Great! I can confirm it works now.
