### ISSUE TITLE
Provide content_without_summary field

### ISSUE THREAD

**Issue by Kingdutch** [getzola/zola#196]
I'd like to display the summary above a Table of Contents before the rest of the content. This is possible with the summary field but if I then simply output the content field it'll include the summary again so it appears on the page twice.

This also provides the usecase where a summary might be a text used for teasers but not necessarily wanted for the article itself.

**Comment by Kingdutch** [comment]
Small update, if you're looking for a workaround that works now:

`{{ page.content | replace(from=page.summary, to="") | safe }}`

**Comment by Keats** [comment]
Hmm I don't think it makes sense to add that seeing there is a one liner workaround. Adding it to Gutenberg would slow down every single site (copying and serialising the content twice) for a kinda niche usecase

**Comment by Kingdutch** [comment]
Yeah I thought of the possibility of the workaround beforehand but only figured out it actually worked afterwards. ^^

I guess there's no performance penalty for this oneliner as it happens at compile time anyway. I'll go ahead and close this :) People can at least find this if they ever need it.

**Comment by codecat** [comment]
Sorry to necrobump a 3 year old thread, but I don't think this is a great workaround - if the summary appears elsewhere in the content it will also be removed. (This is of course a small chance, but still; it's not very reliable.)

I checked the Tera documentation for a `substring` filter for a more reliable method, but all I could find was `truncate` which does the exact opposite of what we want to do here.

Does not having a reliable workaround for this make it more of an interesting feature request? Otherwise, perhaps this would be a good feature request for Tera, instead?

**Comment by woojiq** [comment]
> I checked the Tera documentation for a substring filter for a more reliable method, but all I could find was truncate which does the exact opposite of what we want to do here.

As of now there is the `trim_start_matches` function, [docs](https://tera.netlify.app/docs/#trim-start-matches).
E.g, `{{ page.content | trim_start_matches(pat=page.summary) | safe }}`
