### ISSUE TITLE
add support for stylus

### ISSUE THREAD

**Issue by waozixyz** [getzola/zola#207]
stylus has a more minimalistic syntax + supports writing classical css
are there plans to add stylus support?

**Comment by Keats** [comment]
Sass is supported because there is [libsass](https://github.com/sass/libsass) which we can bind to. Stylus seems to be only JavaScript which makes it impossible.

Even if it were possible, I'm not planning to add another CSS transpiler though. You can still get stylus/less/postcss via node and I'd rather have only one option for anything built-in.
