### ISSUE TITLE
Theme templates that use tera include need the included file in the site templates

### ISSUE THREAD

**Issue by verpeteren** [getzola/zola#208]
I am creating a theme that uses a [tera include](https://tera.netlify.com/docs/templates/#include) on the 'next' branch. Although the included file is also in the theme template directory an error occurs.:

```
Error: Failed to render page '/path-to-site/content/page-that-uses-a-sometheme-template-with-include.md'
Reason: Failed to render 'sometheme/templates/page.html' (error happened in a parent template)
Reason: Template 'filethatneedstobeincluded.html' not found
```

It seems that this problem is behaving in the same way as with the [allready solved macros](https://github.com/Keats/gutenberg/issues/192)

**Comment by Keats** [comment]
I thought I mentioned it in the docs but I can't find it: `include` paths are not rewritten in themes so gutenberg will not find them and they will not work. The reason being that changing those paths would require parsing each template recursively looking for a `Include` node that can be present at any point in any node.
If someone wants to have a go at it, the changes should be in `components/utils/src/templates.rs` in `rewrite_theme_paths`.
Since the Tera version has changed, it should be done on the `next` branch
