### ISSUE TITLE
Understanding macros and templates

### ISSUE THREAD

**Issue by j1mc** [getzola/zola#231]
Hi all - this isn't a bug report so much as a question, and I hope this is an okay place to ask it.

I'm working on a Gutenberg theme, and have been reviewing other themes. With regards to templates, I'd like to have a `navbar` element be a stand-alone template that gets included in other templates.

In other templating systems that I've used, I'd see this included as a "partial" (see [hugo](https://gohugo.io/templates/partials/)) or as an "includes" element (see [jekyll](https://jekyllrb.com/docs/includes/)).

Should I be including my navbar or other similar elements via macros, or via other means? In the templates that I've seen thus far as examples, I didn't get a solid understanding as to whether macros  would be most appropriate, and I wasn't sure after reviewing the [Tera docs](https://tera.netlify.com/docs/templates/#macros), either.

Thanks in advance for your help, and for your work on this project.

**Comment by Keats** [comment]
You have 2 choices: either you use `include` and the included template will get the exact same context as the parent template (equivalent to `{{ partial "header/site-header.html" . }}` in Hugo for example) or you can use macros.
Macros are like functions: they only get the context they are given via arguments so it's obvious what you have in the scope.
I personally prefer macros because of that but in some cases for themes it might make sense to use include just so it's trivial to modify by someone using a theme.

**Comment by j1mc** [comment]
Thank you for the reply.
I'm not sure if it's because I wasn't using it correctly or if there were some other issue, but I tried using macros, and that seems to be working well.
I haven't pushed my work up to any public git repo yet, but will provide info about the theme when I do.
