### ISSUE TITLE
striptags seem to no longer work

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#286]
I was in the process of updating a theme from using 0.2.2 to 0.3.3.  

Version 0.2.2
![image](https://user-images.githubusercontent.com/8846211/38596606-7ea0d44c-3d20-11e8-8cfe-b23315d611c9.png)

Version 0.3.3
![image](https://user-images.githubusercontent.com/8846211/38596602-7930e4de-3d20-11e8-8e22-ea31767baacd.png)

Both have this code:

```
{{ page.content | striptags | truncate }} 
```

However, it seems as though 0.3.3 doesn't strip tags.  This doesn't work either:

```
{{ page.content | striptags }} 
```

**Comment by Libbum** [comment]
I'm not sure if this is a version change thing, but from the looks of what you're trying to do here&mdash;using `| safe` might have the desired effect.

**Comment by Keats** [comment]
I think so too, `{{ page.content | safe | striptags }} ` should work as, without `safe`, the text has escaped tags, not tags.

**Comment by piedoom** [comment]
Cool!  I try that.  I'm wondering, would it be more ergonomic to have `striptags` implicity call `safe`?  I can't imagine a use case where safe wouldn't need to be called.

**Comment by Keats** [comment]
> would it be more ergonomic to have striptags implicity call safe

Not sure about that, I'm not a big fan of implicit behaviours

**Comment by Libbum** [comment]
Yeah, verbosity is probably more important than ergonomics here. Just because there isn't a specific use case now (or at least not one off the top of my head), no doubt someone in the future is going to find it. When that happens it's something that'll need to be separated or split off into another function or a similar extension akin to `| not_safe | striptags` would need to be invented.

A better solution (if you think it's needed) would be extending the documentation so if others come up against the issue they won't get stuck.

**Comment by piedoom** [comment]
Fair enough.  However, I can't imagine a use-case now or in the future that would require `striptags` without `safe`.  It doesn't make sense to me as it always requires content to have tags, otherwise it does nothing.  I'm very much in favor of eliminating implicit behavior, but explicit for the sake of avoiding small implicit things is counter-intuitive, IMO.  I'm wondering, was the opposite behavior shown in the version `0.2.2` was a bug, or a decision that was reverted in future updates?

**Comment by Keats** [comment]
I updated the docs in https://github.com/Keats/tera/pull/278/commits/1f64ef45d0dc035657e9d9e3f7ac9ff48de2d91d that will be published for the next Tera release
