### ISSUE TITLE
Intermitent "serve" hang on FreeBSD

### ISSUE THREAD

**Issue by Freaky** [getzola/zola#362]
Every time I run `gutenberg serve` there's roughly a 50% chance it gets to `Done in <x>ms` and then stops dead.

Seems to be an issue with locking as far as I can tell - one thread is sat waiting to acquire a mutex while everything else is asleep.  Comparing with a functioning process most threads aren't starting.

Will update if I find anything substantive (suggestions on what to look for welcome!)

**Comment by Keats** [comment]
> Every time I run gutenberg serve there's roughly a 50% chance it gets to Done in <x>ms and then stops dead.

Do you mean it doesn't show anything in the terminal anymore later? I don't think I have ever seen that :o

All the code related to `serve` is in `src/cmd/serve.rs`. You could try to reproduce that in 0.3.4 to see if it's caused by the webserver: it now uses actix-web instead of iron but I'm not too sure why that would be the cause.
The multithreading itself uses Rayon, that seems unlikely the issue is in it.

I would probably add some logging around https://github.com/Keats/gutenberg/blob/master/src/cmd/serve.rs#L155-L232 to see where it stops and in `detect_change_kind` to see if changes are still detected.

PS: I published a new version of sass-sys and updated gutenberg `master` so it should build without changes for you now.

**Comment by Freaky** [comment]
Yeah, it just stops before both `Listening for changes` and `Web server is available`.

Tried 0.3.4, with a manually modified Cargo.lock to get the latest sass-sys, and I see exactly the same there, so it's not Actix.

> PS: I published a new version of sass-sys and updated gutenberg master so it should build without changes for you now.

Yes, was right at the top of crates.io when I checked this afternoon!  Master builds out of the box now.  If we can sort out `serve` I'll see about making a port.

**Comment by Keats** [comment]
Does it actually get to https://github.com/Keats/gutenberg/blob/master/src/cmd/serve.rs#L228 (ie can you print `watchers`). This kind of looks like when a server has started and stops the execution of the rest of the program because it blocks which makes me think it's either the webserver (even though we changed to actix, it still uses the same structure) or the websocket server.

Is there any gotcha on threading in Rust in BSDs?

> Master builds out of the box now. If we can sort out serve I'll see about making a port.

Great!

**Comment by Freaky** [comment]
Yeah, I suspected that, but it appears to actually be `notify`; I put logging messages on each call to `watch` and when it wedges it's stopped part way through - not always at the same place.

It looks like it's just using the stock polling backend on FreeBSD, so it's not some weird kqueue thing (indeed ktrace shows no kevent/kqueue calls except on successful runs).  I guess the fallback backend simply isn't exercised very well.

Judging by the "cannot be shared between threads safely" errors from `cargo test`, nor is the test suite...

**Comment by Freaky** [comment]
Yup, confirmed with a small test program with only the most straight-forward usage of notify.

**Comment by Freaky** [comment]
And [pull request upstream](https://github.com/passcod/notify/pull/159).

**Comment by Freaky** [comment]
Fixed in notify 4.0.4.

**Comment by Keats** [comment]
Updated master, let me know if you run into other issues or if everything is ok!

**Comment by Freaky** [comment]
Looks good!  Closing as fixed.
