### ISSUE TITLE
The feature comparison table should use ✓ and ✗ instead of ✔ and ✕.

### ISSUE THREAD

**Issue by bdjnk** [getzola/zola#540]
Instead of using ✔ (U+2714 : HEAVY CHECK MARK) and ✕ (U+2715 : MULTIPLICATION X) in the feature comparison table we should use ✓ (U+2713 : CHECK MARK) and ✗ (U+2717 : BALLOT X).

This will look better everywhere, and in my tests significantly better for Firefox and Safari.

**Comment by bdjnk** [comment]
Here's a **before** (left) and **after** (right) for **Firefox**.

![screen shot 2018-11-28 at 12 36 32 pm](https://user-images.githubusercontent.com/620722/49170519-5371f580-f30a-11e8-8edf-96e9bf0f6173.png) ![screen shot 2018-11-28 at 12 36 03 pm](https://user-images.githubusercontent.com/620722/49170529-5a006d00-f30a-11e8-804a-966445d16a40.png)

**Comment by Keats** [comment]
Could it be your system font?

![2018-11-28-200046_555x701_scrot](https://user-images.githubusercontent.com/680355/49175207-54c21300-f348-11e8-86f5-a3c4532cc04e.png)

It looks the same on chrome/firefox for me

**Comment by piedoom** [comment]
FWIW mine looks the same as @bdjnk's example - I'm using MacOS and I don't believe I would have an override font.  Mine looks like theirs on Safari, FF Nightly, and Chrome.

**Comment by RealOrangeOne** [comment]
Not that I want to encourage a 'Mine looks like $PERSON' thread here, but mine _does_ look like @Keats 's. 

Are both of you using macOS? It's possible this is just how macOS renders those icons by default. 

That being said, if you want to fix it, and it still looks fine on other platforms, I see no reason why a patch couldn't be submitted. One of the great things about OSS.

**Comment by piedoom** [comment]
I'm personally not bothered by it, just thought I'd share in case the information was useful.  It's likely just how Macs render.

**Comment by bdjnk** [comment]
Interesting. It must indeed be MacOS, which I have on my work computer. Now that I'm back home on my Linux machine it looks like what you have @Keats. And unfortunately the change makes it slightly worse, causing it to look like this.

![2018-11-28-173454_439x287_scrot](https://user-images.githubusercontent.com/620722/49186990-20445c00-f334-11e8-933c-c100abf78bd2.png)

Using `⨯` (U+2A2F : VECTOR OR CROSS PRODUCT) instead looks decent on Linux. I'll take a look tomorrow on MacOS.

**Comment by Keats** [comment]
The x looks a bit bad on Linux yeah :(

**Comment by bdjnk** [comment]
Well, ⨯ (U+2A2F : VECTOR OR CROSS PRODUCT) is far too small on MacOS, but ✕ (U+2715 : MULTIPLICATION X) looks good with ✓ (U+2713 : CHECK MARK). And as I recall that combination also looked decent on Linux.

**Comment by chris-morgan** [comment]
Somehow no one’s mentioned U+274C CROSS MARK, which is semantically the best one to use in conjunction with U+2714 HEAVY CHECK MARK because of emoji.

Here’s the full table of *semantically reasonable* options:

<table>
<tr><td>✔</td><td>U+2714 HEAVY CHECK MARK</td></tr>
<tr><td>❌</td><td>U+274C CROSS MARK</td></tr>
<tr><td>✘</td><td>U+2718 HEAVY BALLOT X</td></tr>
<tr><td>✓</td><td>U+2713 CHECK MARK</td></tr>
<tr><td>✗</td><td>U+2717 BALLOT X</td></tr>
</table>

The first two are emoji ([Heavy Check Mark](https://emojipedia.org/heavy-check-mark/), [Cross Mark](https://emojipedia.org/cross-mark/)), the rest aren’t. (Everything’s weird; you’d think U+2718 would have been the one to match U+2714, just like U+2717 is U+2713’s match—but no, emoji went and did its own crazy thing.)

On Windows, the first two look ideal as a pair; the check mark is green, the cross is red, they’re the same size, and style, &c. Similar on Google, reasonable on Samsung (a slightly weak, red tick). Apple’s tick is *weird*, and all the rest are black or muted colours.

At this point I suggest two more alternatives:

1. `<img src="yes.svg" alt="Yes">`, `<img src="no.svg" alt="No">`, `<img src="partial.svg" alt="Partial">` (decide for yourselves what the images will be).

2. “Yes”, “No”, “Partially”, *&c.*

I recommend using images with descriptive alt text.

**Comment by Keats** [comment]
![2018-12-01-132946_292x196_scrot](https://user-images.githubusercontent.com/680355/49328230-31c47880-f56d-11e8-8e49-d30c4b59466a.png)

Yeah I think unicode is not going to work out for all platforms :(
Images are probably the best bet.

**Comment by chris-morgan** [comment]
Here are three small SVG files that I just wrote:

<img src=https://temp.chrismorgan.info/yes.svg alt="Yes" title="Yes">
<img src=https://temp.chrismorgan.info/no.svg alt="No" title="No">
<img src=https://temp.chrismorgan.info/partial.svg alt="Partial (see note below)" title="Partial (see note below)">

What do you reckon?

**Comment by Keats** [comment]
Looks very good to me!

**Comment by Keats** [comment]
@chris-morgan any chance you can do a PR?

**Comment by chris-morgan** [comment]
Yep, shall do.

**Comment by bdjnk** [comment]
@chris-morgan I know you are working on comparison table improvements. I also created [a branch fixing the issue](https://github.com/bdjnk/zola/tree/readme#comparisons-with-other-static-site-generators), using octicon (github icon) svgs.

**Comment by Keats** [comment]
I like @bdjnk approach of keeping it in markdown the most, can you do a PR?

**Comment by chris-morgan** [comment]
There were very good reasons why I went full HTML. For maximum utility, Markdown tables really just don’t work.

**Comment by Keats** [comment]
@chris-morgan Do you mean having the first column as `th`?
