### ISSUE TITLE
crates.io availability?

### ISSUE THREAD

**Issue by ghost** [getzola/zola#557]
Are there plans to add this to the cargo registry? It will help users keep the application up to date in a centralized manner, especially using `cargo install-update`.

**Comment by reillysiemens** [comment]
@evitalis: At one point Zola was in the cargo registry, but it was removed due to issues with shipping binary packages (rust-lang/cargo#2263) and other reasons given by @Keats in #117. The cargo issue has been resolved since rust-lang/cargo#5093, but given the relatively recent response from @Keats  in #392 it doesn't sound like there will be a shift any time soon. Meanwhile, if installing from source is getting too onerous, you might do something like [what I've done for my site](https://github.com/reillysiemens/tuckersiemens.com/blob/d8b3b6e21e1c297a9d3240a9295ef321c5350e22/bin/update-zola).

@Keats: This seems to be a recurring question. Maybe it would be worth adding a note in the source installation instructions pointing to #117 or somehow indicating why [crates.io](https://crates.io/) installation is unavailable?

**Comment by ghost** [comment]
Thanks for the information. I will keep an eye on this as I do get some other binary projects from crates.io. Would it be possible to build update functionality, at least a notification, into zola itself? Would solve knowing when a new version is available, and save the hassle of independent shell scripts for all users.

**Comment by Keats** [comment]
The plan is to use proper package managers to handle updates, so you get new updates with the rest of the packages.
zola is a bit tricky to build on Windows as well so I prefer relying on the pre-built binaries.

I should probably add a note in the "from source" about crates.io as @reillysiemens mentioned

**Comment by ghost** [comment]
Thank you guys for the feedback. I am going to work on an OS specific package for my OS to help ease this issue. I will open a PR with a readme update when this is done and ready.
