### ISSUE TITLE
Use percent encoding for header id

### ISSUE THREAD

**Issue by pbzweihander** [getzola/zola#570]
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior

https://pbzweihander.github.io/arch-linux-installation

I think the id of header `설치 전 할 일` has to be `설치-전-할-일` or `%EC%84%A4%EC%B9%98-%EC%A0%84-%ED%95%A0-%EC%9D%BC`.

## Current Behavior

Zola uses [slug](https://docs.rs/slug/0.1.4/slug/) for making id, so zola makes it as `sseoci-jjeo-hal-il` (as you can see in https://pbzweihander.github.io/arch-linux-installation)

How about using [percent-encoding](https://docs.rs/percent-encoding/1.0.1/percent_encoding/) instead of slug when making id for headers?

**Comment by Keats** [comment]
Good point. The downside is that if you don't have an IME installed for non-latin alphabet you won't be able to type the URL manually. At the same time, if you don't have an IME, you probably don't need to do that. I'm working on multi-lingual sites for the next version so that can probably fit in there as well, I'll try.
