### ISSUE TITLE
Add a help page "Moving from...?"

### ISSUE THREAD

**Issue by Keats** [getzola/zola#611]
To list resources helping to move from other tools since it isn't going to be built as part of Zola.

**Comment by jonblack** [comment]
Here's a python script for moving from Ghost.

It will need some adjusting at the moment because it has a hardcoded URL. It's also hardcoded to always collocate. The nice thing is, it will download images found in the post as well (which is why the URL needs changing).

https://gitlab.com/jonblack/ghost2zola
