### ISSUE TITLE
Contents and structure of README.md, relocation of comparison to other projects

### ISSUE THREAD

**Issue by kravemir** [getzola/zola#630]
I'm search for static site generator, preferring written in Rust, and I've found this project. I wanted to give zola try, but README contains comparison with other projects as it's main part, instead of quick-start.

It is beneficial for users, if README contains quick-start tutorial with commands needed to run things in the repository. That is installation part, and basic usage(creation of new project, build, serving locally) part, without going into details about options.

It's also useful to phrase main focus of project as introduction sentence. For example: Zola is single-binary static site generator focused on ... And, list some main features, can be also bullet list for easier skimming,.. 

I wouldn't put the comparison with other projects to a README, to not make it look, that the primary goal/message of the project is to compare with others, but to be used. So, comparison would be better extracted to a separate file. In README then create a short (3lines) chapter 'history and comparison', which gives brief info about history and comparison and points to file containing detailed comparison.

EDIT: based on @piedoom feedback in comments below.

**Comment by Keats** [comment]
Which bit do you disagree with wrt the Cobalt quote? I haven't looked at it since I wrote that so maybe it's better now.

For the Hugo one, that quote does say the template engine is more powerful than the one for Zola and mentions not liking it is a *personal* opinion.

> Listing of downsides of competitive projects isn't politically, and socially, correct,

First time I'm hearing about that. Are you suggesting every single comparison table is not politically correct? 
I do point out the main downside of Zola when listing the supported content format and I'm happy to add features to that table that Zola does not have.

> For comparison, there are other sites available

Well pretty much everytime this project was posted anywhere, the main questions were how is it different from X or Y so people do want to know these kind of things.

**Comment by kravemir** [comment]
_Removed by author, because hostile, instead of constructive, way of communication was used._

**Comment by piedoom** [comment]
At the risk of continuing a rather unproductive and needlessly hostile conversation, I can't help but offer my  thoughts on the matter. Being said, I don't wish to argue (as GH issues are not the proper place to do that), so this is my one and only.

> when author makes comparison table, or statements, where the author shows downsides of competitive projects. In the end, it's users, who should do the comparison, based on their experiences.

This is quite a remark to make. Nearly every large project has some section with comparisons to similar products. As an amateur end user, I do not want to have to try and test every single competing project just to understand their differences. As a business end user, it's unwise of me to invest time into a technology that I do not understand anything about. 

Every project has pros and cons. Zola, for instance, is meant to be an easy way to get started since it requires no extra tools commonly needed with other gens like Jeykll. Stating the simplicity of a single binary is merely a fact.  It is up to the end user to decide whether or not that feature is helpful in their use case. It shouldn't be up to the user to know whether or not that even *exists* in the first place - that's just a waste of time (and will be documented elsewhere, anyways. Take a look at Slant or AlternativeTo).

> Bashing on the others doesn't make you cool.

I'd like to take a moment to talk about this issue name. Starting from a place of hostility and anger will almost always get your thoughts dismissed, even if they are valid. We are all working towards a common goal: to make great software. Immediately framing your points of view on the offensive makes it difficult for others to want to work together with you. 

I think everything is a learning experience. Instead of what you wrote, consider the following:

> Title: Consider using more neutral language when describing other projects
> Description: I have noticed that the comparisons with Hugo or Cobalt use unfavorable language, such as calling Hugo's templating language "insane". While I respect your personal opinion on the matter, I think it would be more respectful to phrase *why* you dislike Hugo, and why Tera is a better candidate. This will help end users make more educated decisions.

In this format, I phrase the argument in a way that shows I want all parties to benefit (which is really what we all want at the end of the day!) I provide good reasoning, and I don't resort to calling names or making passive aggressive comments. 

Which brings me to this comment:

>  then I care about author's nature and community,... and, people who like to compare themselves with others, are usually the biggest pain in communities,...

I don't think it is ever fair to criticize a maintainer like this, unless they were being objectively hostile. Keats is not - and has never been - hostile. I find Zola to be a remarkable achievement in the Rust space, as well as a model implementation of Rust's own CoC.  

Keats is an excellent maintainer, incredibly respectful, and very active on this repository. It is unfair and rather selfish to remark that someone providing enterprise level support for a free project is a "pain", especially when you started out an issue with unwarranted hostility of your own.

**Comment by kravemir** [comment]
> > Bashing on the others doesn't make you cool.
> 
> I'd like to take a moment to talk about this issue name. Starting from a place of hostility and anger will almost always get your thoughts dismissed, even if they are valid. We are all working towards a common goal: to make great software. Immediately framing your points of view on the offensive makes it difficult for others to want to work together with you.
> 
> I think everything is a learning experience. Instead of what you wrote, consider the following:
> 
> > Title: Consider using more neutral language when describing other projects
> > Description: I have noticed that the comparisons with Hugo or Cobalt use unfavorable language, such as calling Hugo's templating language "insane". While I respect your personal opinion on the matter, I think it would be more respectful to phrase _why_ you dislike Hugo, and why Tera is a better candidate. This will help end users make more educated decisions.

You're right. I should have picked more constructive title, which is focused on the constructive part of idea, not on point which is criticized.

Title: Contents, structure of README.md, and relocation of comparison
Description: `README.md` misses brief information about software in the repository, quickstart tutorial how to run things inside the repository,... That information helps people deciding to give it a try, and also provides them quick way to do it, before they dive into docs... However, README.md contains mostly comparison with other competitive projects, and criticism of them. I am perfectly fine with comparison to other projects, but making it the biggest part of the README.md, which makes it look, that comparison with others is author's primary focus. It would be better to extract it to separate file, and point to it from 'history and comparison' chapter of the README.md.

> In this format, I phrase the argument in a way that shows I want all parties to benefit (which is really what we all want at the end of the day!) I provide good reasoning, and I don't resort to calling names or making passive aggressive comments.

Thanks for info. How would you define the format in abstract / universal way? My goal is to make software, including documentation, better. So, I'd like to learn in communication, and find useful resources.

> Which brings me to this comment:
> 
> > then I care about author's nature and community,... and, people who like to compare themselves with others, are usually the biggest pain in communities,...
> 
> I don't think it is ever fair to criticize a maintainer like this, unless they were being objectively hostile. Keats is not - and has never been - hostile. I find Zola to be a remarkable achievement in the Rust space, as well as a model implementation of Rust's own CoC.

I shouldn't have made association. Even though, people constantly comparing with others, instead of doing their job, are pain in ass,... This doesn't automatically make the author to be one of them.

> Keats is an excellent maintainer, incredibly respectful, and very active on this repository. It is unfair and rather selfish to remark that someone providing enterprise level support for a free project is a "pain", especially when you started out an issue with unwarranted hostility of your own.

I'm sorry for words against Keats. My intention was to make project's README.md better, more focused on users. But, my words were different, hostile, as you said. Thank you for standing up for Keats, and for feedback provided in constructive way.

**Comment by kravemir** [comment]
@piedoom I did rewrite the title and the description, in (hopefully) constructive language, to match my intentions. I hope, I did better/good job now. Feedback is welcome!
