### ISSUE TITLE
Look into Azure Pipelines (or other CI)

### ISSUE THREAD

**Issue by Keats** [getzola/zola#689]
It would be nice to have all 3 environments (Mac, Linux, Windows) on the same provider. Bonus points if there are others.

It also needs to be able to upload the generated binary zipped to GitHub releases

**Comment by janbaudisch** [comment]
Travis seems like a good fit. They have Windows builds in early access and they work quite well with Rust.

I created a Travis [config](https://github.com/flyingP0tat0/zola/blob/master/.travis.yml) on my fork. Here are the builds:

 - [Commit](https://travis-ci.com/flyingP0tat0/zola/builds/115399781)
 - [Tag](https://travis-ci.com/flyingP0tat0/zola/builds/115404066)

(Build times are somewhat long, but this will be resolved once I configure the caching correctly.)

Windows builds are disabled right now, because libsass does not build on Travis. This problem is fixed on the libsass side of things, and they might release a patch update ([I asked for it](https://github.com/sass/libsass/issues/2906)). With the fixed libsass I was able to build sass-rs on Travis for Windows: [Build](https://travis-ci.com/flyingP0tat0/sass-rs/builds/114977260).

In my opinion, the clear advantage of Travis is the simple configuration.

There are two options:

```
Linux { stable, beta, nightly }
osx { stable, beta, nightly }
Windows { stable, beta, nightly }
Tag: deploy (each platform on stable release)
```

An alternative with fewer builds and therefore faster CI runs:

```
Linux { stable, beta, nightly }
osx { stable }
Windows { stable }
Tag: deploy (each platform on stable release)
```

If the extra build time is no concern, the first approach might be the better one.

I think Travis could be a good fit for all three platforms.

**Comment by Keats** [comment]
So the main reason to look for other platforms was also to potentially move out of Travis since they got acquired and https://news.ycombinator.com/item?id=19218036

> This problem is fixed on the libsass side of things, and they might release a patch update (I asked for it). With the fixed libsass I was able to build sass-rs on Travis for Windows:

Amazing! Hopefully it will make sass-rs easier to build for everyone as well.

**Comment by Keats** [comment]
I've set up a fully working CI setup for Azure Pipelines: https://github.com/Keats/azure-pipelines-test after being fed up with the apparently new failures in linux CI on travis on the next branch...
I might switch Zola to it later

**Comment by Keats** [comment]
Working PR: https://github.com/getzola/zola/pull/750

The main downside is that sass-sys takes 10 minutes to compile on Windows (!!). I still need to check if I can cache it. The builds are faster even without caching anyway.

**Comment by Keats** [comment]
It's now using Azure pipelines
