### ISSUE TITLE
get_section global function & sort sections

### ISSUE THREAD

**Issue by pka** [getzola/zola#69]
Hi!
I'm creating a documentation site for my Rust project. I'm stuck at implementing an index side bar with all section&page titles. My content looks like this:

```
├── doc
│   ├── _index.md
│   ├── intro.md
│   ├── configuration
│   │   ├── advanced.md
│   │   ├── basic.md
│   │   └── _index.md
│   └── setup
│       └── _index.md
└── _index.md
```

With a global `get_section` function I could iterate through all subsections of `doc` and their pages. As an alternative solution, a page could return the section it belongs to. Then I could start with the `intro.md` page.

On the current section/page I also want to display links to the previous and next section/page. See https://rocket.rs/guide/ as an example. This should be possible with a `get_section` function, but maybe an additional helper would make sense for that.

Thanks for your work - it looks very promising to me!

**Comment by Keats** [comment]
I actually want to do a site very similar to the rocket guide you linked for Tera.

My approach was to do the sidebar manually in the template like so:
```
    <aside>
        <ul>
            <li><a href="/introduction">Introduction</a></li>
        </ul>
        <ul>
            <li><a href="/getting-started">Getting started</a></li>
        </ul> 
     ...
    </aside>
```
With the hardcoded links replaced by a `get_url` (#67). This is little bit manual since you have to update the template if you change a section but in practice it doesn't happen very often.
Using this approach we can do something like:

```
    <aside>
        <ul>
            <li><a href="{{ get_url(page="./doc/configuration.md) }}">Configuration</a></li>
            <ul>
                <li><a href="{{ get_url(page="./doc/configuration.md#basic) }}">Basic</a></li>
                <li><a href="{{ get_url(page="./doc/configuration.md#advanced) }}">Advanced</a></li>
             </ul>
        </ul>
        <ul>
            <li><a href="/getting-started">Getting started</a></li>
        </ul> 
     ...
    </aside>
```
which gives you exactly the rocket design (I put both basic and advanced part of configuration.md, it might be incorrect in your case though).
You also should get the direct subsections of `doc` as `section.subsections` in its template 

For the previous/next sections, that implies sorting sections as well somehow and that's a very good usecase! I'll think about it

**Comment by Keats** [comment]
I actually just realised that to do the same layout as rocket, it's already possible as each "section" in the rocket guide is a page.
Do you know if the rocket site repo is publicly accessible? I'm curious how it's set up

**Comment by pka** [comment]
In the meantime I've also switched from sections to pages and added this to the template:
```
{% set toc = get_page(path="/toc.md") %}
{{ toc.content | safe }}
```
I still think that sections should have more page functionality like get_section and previous/
next.

The rocket doc content is at https://github.com/SergioBenitez/Rocket/tree/master/site, but the HTML generation code seems not be public.

**Comment by Keats** [comment]
I agree! the `get_section` will probably be in the next version and maybe sorting for sections as well
