### ISSUE TITLE
Update actix-web to 1.0.0

### ISSUE THREAD

**Issue by igor-raits** [getzola/zola#701]
It is still release candidate, but that makes it very close. So finally another dependency which reached 1.0 :)

I would appreciate this to be done asap so that I can package zola for Fedora.

Thanks!

**Comment by Keats** [comment]
I will update once it reaches 1.0.0

**Comment by igor-raits** [comment]
@Keats I would appreciate much if you could supply me with some patch which just uses pre-release version so that I can get zola in few days in fedora.

**Comment by Keats** [comment]
Which version of Zola would be packaged? I'm personally not going to update Zola to actix 1.0 until it gets released

**Comment by igor-raits** [comment]
I'm fine with taking latest git commit and just packaging that... and if there is some patch to get actix 1.0 support, I would just apply that on top.

**Comment by igor-raits** [comment]
@Keats, 1.0.0 Is out

**Comment by Keats** [comment]
Whoa some of it got really messy: https://github.com/actix/examples/blob/master/middleware/src/simple.rs
If anyone is more familiar with actix than me, I'll take a PR

**Comment by igor-raits** [comment]
@fafhrd91 if you have any time, would be much appreciated :)

**Comment by samford** [comment]
Hi!  I've been working on upgrading Zola's serve command to use actix_web 1.0.0 and I have a functioning version (serving static files, LiveReload, handling index.html files) except for the previous `NotFoundHandler`.  I tried to see if anyone in the Actix Gitter could provide some guidance in terms of creating a `NOT_FOUND` handler that returns a static 404.html file (using a path specified at runtime) but sadly I didn't receive a response and my question is now quite buried.

At this point, I've created three different implementations of a `NOT_FOUND` handler, each of them with some sort of issue.  With two of them, I can't figure out how to pass the 404.html path to the handler (like `static_root.join("404.html")` was provided to the old `NotFoundHandler`).  In another, I've run into a lifetime error that I can't seem to resolve and that implementation is stuck there.

I created a repository containing small, standalone implementations ([actix-notfound-handler-tests](https://github.com/samford/various-tests/tree/main/actix-notfound-handler-tests)), if anyone would like to take a look and offer advice on how to resolve the issues I'm currently wrestling with.  There are notes in the README files and in each main.rs file.

If we can find a solution for the `NOT_FOUND` handler, then I can wrap up the upgrade and create a pull request for review.

**Comment by fafhrd91** [comment]
@samford there are two options:

1. register handler for `/*` path
2. use `App::default_service()`

**Comment by samford** [comment]
@fafhrd91 Thank you for the response.  I had noticed the use of `App::default_service()` in the [basics](https://github.com/actix/examples/tree/master/basics) example but I was trying to avoid it, since it works as a catch-all and doesn't distinguish between `StatusCode`s.  The current `NotFoundHandler` in Zola includes an `if http::StatusCode::NOT_FOUND == resp.status()` conditional and I've been trying to faithfully replicate that behavior.

Of what I've tried so far, it seems like using `ErrorHandlers` would be ideal but I don't see a way to get the 404.html path into the handler.  For example, I can use `App::data()` to provide the 404.html path to a route in `default_service()` but this doesn't appear to work in the same way for an `ErrorHandlers::handler()` (i.e., placing `.data(static_root.join("404.html"))` before `.wrap(error_handlers)` and adding a `web::Data<PathBuf>` parameter to the handler).  Is something like this currently possible?

That said, I've added an additional implementation using `default_service()` (found in the [actix-test-default-service](https://github.com/samford/various-tests/tree/main/actix-notfound-handler-tests/actix-test-default-service) folder of the aforementioned repository) and it works as expected.  It may be that this ends up being fine for Zola (if we don't need to distinguish between error codes) but I wanted to at least *try* to match the functionality of the existing code.  Do you have a preference, @Keats?

**Comment by samford** [comment]
After searching through Actix issues and documentation, it appears that you can access `App::data` in an `ErrorHandlers::handler()` using `res.request().app_data()`, so I was able to modify the [`ErrorHandlers` implementation](https://github.com/samford/various-tests/tree/main/actix-notfound-handler-tests/actix-test-errorhandlers) such that it's similar to the `default_service()` implementation.

The difference between the two is that the `ErrorHandlers` version only handles `StatusCode::NOT_FOUND` (in line with the existing `NotFoundHandler`) whereas `default_service()` seemingly responds with 404.html to any error.  With `ErrorHandlers`, you could add additional handlers for different status codes in the future (e.g., 5xx status codes), if desired.

Once I hear which behavior is more desirable, I'll wrap up these changes and create a pull request.

**Comment by Keats** [comment]
The server in Zola is extremely basic, it's basically either 200 or 404. No one should be using it in production (what would be the point of a static site generator then).
The ErrorHandlers approach seem more logical though so let's go with that.

Thanks a lot @samford and @fafhrd91 !

**Comment by samford** [comment]
This is *so* very close to being finished but now that I've added the `ErrorHandlers` code to serve.rs, I'm getting an error that doesn't appear when building the current version of the [`ErrorHandlers` test implementation](https://github.com/samford/various-tests/tree/main/actix-notfound-handler-tests/actix-test-errorhandlers) or the [actix_todo example](https://github.com/actix/examples/tree/master/actix_todo).  The error is as follows:

```
error[E0271]: type mismatch resolving `<fn(actix_web::dev::ServiceResponse<_>) -> std::result::Result<actix_web::middleware::errhandlers::ErrorHandlerResponse<_>, errors::Error> {cmd::serve::not_found::<_>} as std::ops::FnOnce<(actix_web::dev::ServiceResponse<_>,)>>::Output == std::result::Result<actix_web::middleware::errhandlers::ErrorHandlerResponse<_>, actix_web::Error>`
   --> src/cmd/serve.rs:191:22
    |
191 |                     .handler(http::StatusCode::NOT_FOUND, not_found);
    |                      ^^^^^^^ expected struct `errors::Error`, found struct `actix_web::Error`
    |
    = note: expected type `std::result::Result<actix_web::middleware::errhandlers::ErrorHandlerResponse<_>, errors::Error>`
               found type `std::result::Result<actix_web::middleware::errhandlers::ErrorHandlerResponse<_>, actix_web::Error>`

error: aborting due to previous error
```

This error occurs even if `not_found()` simply returns `Ok(ErrorHandlerResponse::Response(res))`.

The only relevant change from the current standalone `ErrorHandlers` implementation is that I removed `actix_web::Error` from the `not_found()` `Result` return type.  For whatever reason, the standalone version gives an error if there's only one argument in the `Result` even though the return type is normally `Result<ErrorHandlerResponse<B>>`.  This is the return type you find in the actix_web documentation, actix_todo example, and in my updated version of Zola's serve.rs.

As an aside, I've since refactored the `ErrorHandlers` implementation to use a struct for providing paths to error HTML files (since it allows for easier modification if additional `ErrorHandlers` are ever added in the future) but this doesn't appear to be the source of the error (since the standalone version uses the same setup and will build and run without errors).

You can find the current state of this update in the [actix-1.0 branch of my Zola fork](https://github.com/samford/zola/tree/actix-1.0).  If anyone would like to try their hand at resolving this error, please feel free.  It's probably something simple but I've been looking at this for too long and can't see it.

**Comment by Keats** [comment]
This error is because you are using `Result` for the handler which is the pre-built Result of Zola, expecting a Zola error type. Switch the not found handler result to be `std::result::Result<ErrorHandlerResponse<B>, actix_web::Error> `.
You do get a borrowing issue after fixing that though.

**Comment by samford** [comment]
Ah! Thanks for that.  I resolved the borrowing issue by creating `buf` in a block, so the borrow that's created by `res.request()` goes out of scope before `res` is used in the return.  This is incorporated into my actix-1.0 branch.

Everything compiles and runs as expected now and the tests pass.  In my limited manual testing, the HTTP responses are in line with the "next" branch (using actix-web 0.7).

The only thing left is that we now have a warning from `s.run()`, which doesn't occur with actix-web 0.7:

```
warning: unused `std::result::Result` that must be used
   --> src/cmd/serve.rs:218:13
    |
218 |             s.run();
    |             ^^^^^^^^
    |
    = note: #[warn(unused_must_use)] on by default
    = note: this `Result` may be an `Err` variant, which should be handled
```

The Actix examples tend to follow a pattern where `HttpServer::new().run()` occurs at the end of `main()` and is returned (with `main` having a function signature like: `fn main() -> std::io::Result<()>`).  How would you like to handle this `Result` in Zola?

**Comment by Keats** [comment]
Probably match on that result and abort with the message if there is an error

**Comment by samford** [comment]
Like this or did you have something different in mind?

```rust
match s.run() {
    Ok(_) => (),
    Err(e) => panic!("Can't start the webserver: {:?}", e),
}
```

When I tested this in a way that would trigger an error condition (i.e., running a process on a specific port and forcing Zola to use the same port), it predictably kills the thread the Actix server runs on and prints the error but Zola keeps running until you press Ctrl+C.

```
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
Done in 29ms.

thread '<unnamed>' panicked at 'Can't start the webserver: Os { code: 48, kind: AddrInUse, message: "Address already in use" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Listening for changes in /some_folder/{content, config.toml, static, templates, sass}
Press Ctrl+C to stop
```

Some users might overlook the panic error, since Zola's still running and they see the usual "Listening for changes...Press Ctrl+C to stop" text, then wonder why the server isn't responding.  As a user, I would expect Zola to quit at this point, doing the same thing as when you press Ctrl+C (deleting the output directory before exiting).

I did some experimentation, using [`std::panic::set_hook`](https://doc.rust-lang.org/std/panic/fn.set_hook.html) to handle this, but it appears to prevent the panic in the Actix thread from displaying its error text and it doesn't seem like any `panic_info` from the Actix thread is passed to the hook in the main thread (so we can't display the error there either).  As a result, I could only provide generic output like "Can't start the webserver. Quitting...", which isn't very helpful without the error to explain *why* the webserver couldn't start.  Maybe there's a way around this but I haven't dug too deeply into it.

I'll post the code if you're interested but I'm definitely not an expert here and there might be a better way to deal with this, so I think it's probably better to leave the implementation up to you.  The match on `s.run()` above is enough to deal with the previously-discussed warning and it will probably be rare for users to run into an error at this point anyway (since Zola already switches ports if the default is in use).

The additional error handling can always be dealt with later, as a separate issue from this one, and I don't want to unnecessarily hold up the actix-web update.  If you're fine with the code for handling the `s.run()` result above, then I'll add it to my branch and create a pull request.  Otherwise, just let me know of any changes you would like.

**Comment by Keats** [comment]
Ah, I forgot it had its thread. If the only possible error is the port already taken, then we can safely ignore it since it won't happen. I guess `::std::process::exit(1);` only exits the actix thread?

**Comment by samford** [comment]
Seems right.  The [Actix documentation for `HttpServer::run`](https://docs.rs/actix-web/1.0.0/actix_web/struct.HttpServer.html#method.run) says "This methods panics if no socket addresses get bound".  I had to disable Zola's port-handling code in `main.rs` and hardcode a port number to test the error handling, so I doubt users would ever run into this error.

Yep, since the match code is within the Actix thread, substituting `std::process:exit(1)` just exits the Actix thread as well (same as with `panic`).  If you want Zola to exit altogether you have to handle the panic outside of the Actix thread.  I was using `std::panic::set_hook` [outside of the Actix thread] to catch the panic that occurs in the Actix thread and then run the same code that occurs in `ctrlc::set_handler`.

That said, I was just looking at the documentation for `panic::PanicInfo` and apparently it implements `Display`, so I tried printing it from `panic::set_hook` and, sure enough, the error from the Actix thread's panic was there after all.  [I was using `panic::PanicInfo::payload` before, like in the payload example, and that wasn't displaying anything.]

As an aside, apparently we can avoid the result matching in the Actix thread if we simply return `s.run()` (it's currently `s.run();`).  As mentioned above, `actix_web::HttpServer::run` will panic if it runs into a problem and we can simply handle the panic using `panic::set_hook`, same as the panic from the match but with less code.

This `panic::set_hook` setup currently looks like this (with the exit code from `ctrlc::set_handler` refactored into a closure):

```rust
pub fn serve(
    ...
) -> Result<()> {
    let serve_exit = |output_path: &PathBuf, code: i32| {
        remove_dir_all(&output_path)
            .expect("Failed to delete output directory");
        ::std::process::exit(code);
    };

    ...

    let broadcaster = if !watch_only {
        let yet_another_output_path = output_path.clone();
        std::panic::set_hook(Box::new(move |panic_info| {
            println!("{}", panic_info.to_string());

            console::info("Error encountered. Quitting...\n");
            serve_exit(&yet_another_output_path, 1);
        }));

        thread::spawn(move || {
            ...
            s.run()
        });

        ...
    };

    ...

    ctrlc::set_handler(move || serve_exit(&output_path, 0))
        .expect("Error setting Ctrl-C handler");

    ...
}
```

Without an error condition, the output's as expected.  With an error condition (address already in use), the output's something like:

```
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
Done in 151ms.

Listening for changes in /some_folder/{content, config.toml, static, templates, sass}
Press Ctrl+C to stop

panicked at 'Can't start the webserver: Os { code: 48, kind: AddrInUse, message: "Address already in use" }', src/libcore/result.rs:997:5
Error encountered. Quitting...
```

The panic error and "Error encountered. Quitting..." text can appear above, below, or around the "Listening for changes...Press Ctrl+C to stop" text, depending on how things shake out.  It would be nice if we could exit before the "Listening for changes..." text even appears but I haven't yet looked into whether that's possible.  At the very least, "Error encountered. Quitting" is printed using `console::info`, so it should be eye-catching (where available).

I'm sure there are things that might need to be finessed (`yet_another_output_path` needs a real name and maybe there's a better way of handling the exit code reuse between `panic::set_hook` and `ctrlc::set_handler`) but what do you think about this setup?  If there's anything about this implementation that you would like changed (functional or cosmetic), just let me know.

Of course, the `panic::set_hook` setup is only necessary if you want to gracefully handle the error (quitting Zola if Actix panics without requiring the user to press Ctrl+C).  If you're confident that Zola will never run into an error here, I can just modify `s.run();` to `s.run()` and we're good to go.

**Comment by Keats** [comment]
I think, let's just print some message saying to restart zola or file a bug and just ignore everything else. So at least the failure is not entirely silent.

**Comment by samford** [comment]
I think it would probably be best if I simply went ahead with a pull request for the Actix 1.0 update and you'll be free to handle this however you would like after merging.  I fear that I'm dragging this on and I don't wish to hold this up any longer than necessary.

My actix-1.0 branch currently compiles without errors or warnings, passes the existing tests, and works as expected (through manual testing), so I don't think there's anything notable standing in the way at this point.  I'm returning `s.run()` from the Actix thread (which resolves the warning) and a panic from `actix_web::HttpServer::run` will output the panic error, so silently failing isn't a concern (though users will still have to manually quit Zola after the panic).

If this is fine with you, I'll create a pull request for this.

**Comment by Keats** [comment]
Go for it!

**Comment by igor-raits** [comment]
@Keats @samford thanks folks! This made zola possible for packaging for Fedora.

I've already done so and soon (up to week) it should be available.
