### ISSUE TITLE
`anchor-link.html` template doesn't reload on `zola serve`

### ISSUE THREAD

**Issue by ralfbiedert** [getzola/zola#719]
# Bug Report

## Environment

Zola version: 0.8.0

## Expected Behavior
When editing `anchor-link.html` while running `zola serve` the rendered page should contain the new anchors, not the old ones. 

## Current Behavior
Right now I have to `ctrl-c` zola and start it again to see the result of my edited `anchor-link.html` in my final output.

## Step to reproduce
Right now, for example when editing cheats.rs:

- add `templates/anchor-link.html` with content `XXX`
- add `insert_anchor_links = "right"` to `_index.md`
- run `zola serve`
- change `templates/anchor-link.html` to contain `YYY`
- console will print:

```
Change detected @ 2019-06-24 08:24:24
-> Template changed D:\Development\Source\cheats.rs\templates/anchor-link.html
Done in 11ms.
```

- however, old anchor text `XXX` is still rendered.

**Comment by Keats** [comment]
I'm not sure what should be done in that case, re-render the whole site?

**Comment by apiraino** [comment]
Isn't however what already happens when I update a css or a sass? Aren't these changes applied on the whole website? I even have multiple tabs refreshing because the local websocket works very well.

The output of `zola serve` registers changes to the _index.md so this could trick into expecting the website to update.

I then lookely closely at the documentation, there is a quick mention about manually restarting `zola serve` in case not all content is refreshed.

**Comment by Keats** [comment]
> Isn't however what already happens when I update a css or a sass? Aren't these changes applied on the whole website? I even have multiple tabs refreshing because the local websocket works very well.

Not really. The websocket replaces the css lives but changes on a template will need to re-render the template in Zola.

The current `zola serve` is pretty terrible and hopefully something better will be written; that's the goal for the next release. Maybe something like https://zola.discourse.group/t/virtual-file-system/415/3
