### ISSUE TITLE
escaped linebreak produces backslash instead of <br> tag

### ISSUE THREAD

**Issue by southerntofu** [getzola/zola#760]
# Bug Report

Trying to build a page imported from an etherpad lite instance, passing its HTML export through pandoc to obtain the Markdown. pandoc escapes the linebreaks in the Markdown output so the end of the page looks like this:

```
last line\
\
```

## Environment

Zola version: next branch

## Expected Behavior

The page should render to ```last line<br /><br />``` according to [commonmark example](https://spec.commonmark.org/0.29/#example-302).

## Current Behavior

The page renders to ``last line<br />\``` so there is a visible backslash at the end of the article. 

## Step to reproduce

Put a backslash right before the end of the last line. It gets rendered to a backslash, not a line break.

**Comment by Keats** [comment]
I didn't know that was a thing. That does look like a markdown parser issue though, from https://github.com/raphlinus/pulldown-cmark
Running your example in https://spec.commonmark.org/dingus/?text=foo%5C%0Abar%0A gives me a different result than your expected behaviour though.
I'm going to close this as it's very unlikely to be an error coming from Zola, please open an issue in pulldown-cmark instead.

**Comment by southerntofu** [comment]
Ok so in the meantime i realized this is [according to spec](https://spec.commonmark.org/0.29/#example-641) and not a bug!

My solution was to use pandoc `commonmark` mode and not `markdown` so it doesn't escape the line breaks like that. Like this:
```
pandoc foo.html -f html -t commonmark -s -o foo.md --wrap=preserve
```
