### ISSUE TITLE
Underscores in slugs get converted to hyphen-minus and other slugification issues

### ISSUE THREAD

**Issue by chris-morgan** [getzola/zola#768]
I have a content file named `rust-cfg_attr.md`  on my Zola 0.8.0 site.

Zola ignores what I deliberately typed as the slug, and turns the `_` into `-`, yielding `rust-cfg-attr`. This makes me unhappy.

I expect Zola to make no modifications at all to the slug that I specify, so that I can do things how I want to, e.g. `Do_things_like_Wikipedia` if I really want to.

**Comment by Keats** [comment]
It looks like the "slug everything" approach is too strong. It should instead only remove some characters like `&` or `/` from the slug. This will give us UTF-8 slugs as well, which are transformed into ASCII right now.

Anyone interested in doing that?

**Comment by chris-morgan** [comment]
Why change anything? `&` is perfectly fine in URLs, and you won’t encounter `/` in filenames.

I’m interested in fixing this.

**Comment by Keats** [comment]
From https://en.wikipedia.org/wiki/Percent-encoding I would prefer to stick with the unreserved characters + UTF8 since otherwise things like & needs to be encoded for the sitemap. I had a quick test with Hugo and the resulting slugs are exactly what I expected so it might be as simple as porting their slug code from Go to Rust.

**Comment by chris-morgan** [comment]
Yes, ampersand will need to be encoded everywhere, just as would already happen; I fail to see why that would be a problem.

I see no reason why we should alter what the user has deliberately chosen.

**Comment by Keats** [comment]
It will fail to work in some tools and users might not be aware of encoding, no reason not to remove reserved characters imo: generated URLs by Zola should work everywhere out of the box.

The Go code for Hugo is https://github.com/gohugoio/hugo/blob/master/helpers/path.go#L136 which raised the issue of what to do with accents in paths. I think we want to remove them (at least I wouldn't want them in a French page for example) but need to be careful to not remove other languages significant "accents" like `ビ` in Japanese and replace it with the correct ASCII version, `ä` in German should become `ae`, not `a`. 
I don't know whether an option like `RemovePathAccents` in Hugo is required though, it feels like the default should be `true` and I'm pretty sure the option is only there for backwards compatibility. 

A related issue: https://github.com/getzola/zola/issues/570

**Comment by chris-morgan** [comment]
What tools do you have in mind where things might fail?

I maintain that these aren’t things that Zola chose. These are things that the *user* chose, and Zola should emphatically be leaving them alone. Removing things like accents would be *wrong*. Messing with what the user provided *at all* is *wrong*.

**Comment by Keats** [comment]
> What tools do you have in mind where things might fail?

Latex for the first thing that comes to mind. Try to put an accent in a URL like https://fr.wikipedia.org/wiki/Wikipédia and it's going to fail, the user will need to manually encode the accents. Many tools in various places do assume ASCII only URLs. I've seen forums where a link to a Wikipedia article with an article would stop before an accent, linking to a 404 for example.

> Removing things like accents would be wrong. Messing with what the user provided at all is wrong.

I would disagree on that. I guess it's more common with taxonomies, but I would want to write the proper name for one, like `cinéma` without wanting to have the é in the URL. I think it's a pretty common need, as seen in https://discourse.gohugo.io/t/special-characters-in-taxonomy/1247/14

Another thing that sucks with non-ASCII urls is the sharing, eg the Japanese homepage of Wikipedia is https://ja.wikipedia.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8 when you copy the link which is unreadable and gets long very very easily :/ This is the main reason I (and others from the thread above I guess) do not want accents.

**Comment by chris-morgan** [comment]
But I repeat: *this is something that the user chose*. If I put an accent in the filename, *I expect it to stay there*. If I wrote my URLs in Japanese, *I expect them to *be* in Japanese*.

It is not Zola’s place to interfere in these matters.

For comparison, consider IDNs.

Changing these things at all is wrong.

**Comment by Keats** [comment]
Right but as I said, I might want to have the correct spelling for a word as a taxonomy but not have any of its accents in the URL (only for ASCII accents, Japanese will not get escaped). So there needs to be an option to at least remove accents (the `RemovePathAccents` in Hugo I guess).

I still need to think for all the URL reserved characters like `&` as I still think they should be removed.

**Comment by chris-morgan** [comment]
I had actually completely forgotten about the slugification of taxonomies, because I don’t use it that way. I will allow that taxonomy terms should have optional (enabled by default) slugification, but that nothing that is already a file name should be touched.

Here’s an excerpt of how I do tags:

```toml
[[taxonomies]]
name = "tags"
rss = true

[extra.tags]
	[extra.tags.rust]
	name = "Rust"
	title = "The Rust programming language"
	description = "I write about Rust things routinely. Here they all are."
```

My pages then have the `"rust"` tag, and templates render it all to `<a href="/tags/rust/" title="The Rust programming language">Rust</a>` or whatever, by looking up values in the config.

**Comment by Keats** [comment]
I would like to have some feedback on the file slugification from other users but if you have time to make a patch it would be much appreciated. With or without the taxonomies option.

**Comment by Keats** [comment]
> taxonomy terms should have optional (enabled by default) slugification

I asked a French speaker on another issue for a tag named `Décentralisation` and they wanted to keep the é if possible so it seems that maybe the default should be to not slugify.

**Comment by southerntofu** [comment]
Hi, i had this problem so i proposed a patch in #781 

When slugify is set to true in config, it does the slugification like before. Otherwise simple sanitation, removing &  and / from the path as mentioned in this discussion. Removing `/` is not useful when parsing from filename but is when parsing from `slug: foo/bar` frontmatter. Maybe remove `#` too?

For the moment the setting defaults to false but in my opinion respecting user-supplied filenames out-of-the-box is less confusing to new users (especially non-english speakers).

In this patch the slugify config affects both page and taxonomy paths. Heading URI fragments (within the Markdown) are left untouched because i have no idea what should be done with those.

**Comment by Keats** [comment]
I think it needs a few more things. To put all the requirements in a list:

1. Filenames are never changed (except for 3)
2. Taxonomies names are never changed unless `config.slugify` (or whatever name) is set to true (except 3). This config value defaults to false.
3. Always remove all `/` and any other characters that can cause issues (`#`?, `?`?) for filenames/taxonomies/hardcoded slugs

@chris-morgan is that accurate?

One thing to ensure is that we get all the cases correctly since that's a big breaking change: some external links to people Zola site would break by default if they had non ascii characters.
I'm on holiday next week but if @southerntofu and @chris-morgan and anyone else reading this issue can work together on a patch that would be great.

**Comment by southerntofu** [comment]
> some external links to people Zola site would break by default if they had non ascii characters

In order to avoid this, i'm proposing:

1. Filenames are slugified if `config.slugified` is true, otherwise never changed (except for 3)
2. slugs passed through a `slug` frontmatter are never changed (except for 3)
2. Taxonomies names are slugified if `config.slugify` is set to true, otherwise never changed (except for 3).
3. Always remove all / and any other characters that can cause issues (`#`?) for filenames/taxonomies/hardcoded slugs
4. `config.slugify` defaults to false so UTF-8 URIs work by default

So turning on `slugify` in the config preserves previously-generated URLs, except for those generated from the `slug` frontmatter which i think should not have happened in the first place. Should those be slugified as well when the config is turned on? (that would enable 100% backwards-compatibility with the flip of a config setting)

The CHANGELOG could then contain a breaking change as such:

> - [Slugification](https://en.wikipedia.org/wiki/Slug_(web_publishing)#Slug) of page paths is now optional. By default, non-ASCII characters (international characters i.e. UTF8) will be retained in the generated pages. If you are currently using non-ASCII characters in your content file paths and want to keep the URLs Zola previously generated, set `slugify = true` in your `config.toml`. **NOTE:** even with `slugify = true`, slugs passed via the `slug` frontmatter key will not be slugified.

> any other characters that can cause issues (#?, ??)

I have no idea about the `#`, but i'm confident we should leave the `?` in place. It is an inoffensive character, and it's a common pattern to simulate GET queries via a `?` within a static file's name, for example for cache-busting purposes.

I'm not sure about `#` because according to HTTP RFC the client never sends this part of the URI to the server so i don't think allowing it as part of a generated URL is a clever idea.

> I'm on holiday next week

Enjoy! I'll be happy to prepare the patch for when you return. If @chris-morgan or others wants to contribute to the patch and docs, i'll take PRs [here](https://github.com/southerntofu/zola/tree/maybe_slugify).

**Comment by Keats** [comment]
> but i'm confident we should leave the ? in place. It is an inoffensive character, and it's a common pattern to simulate GET queries via a ? within a static file's name, for example for cache-busting purposes.

I'm not sure if it can be in a path though. `?` starts the query component so I don't think https://some-site.com/blog?/hello/ is a valid URL for Zola since the query would be `?/hello/` but this isn't what people using Zola would want.
I think we need to remove all of `?, /, #` from paths.

As for the config name, I think `slugify_paths` might be better since `slugify` is a bit too generic.

**Comment by Keats** [comment]
Another thing that will need to change is the slugification of anchors. Probably just a matter of replacing spaces with `_` like Wikipedia does and leaving everything else the same?

**Comment by southerntofu** [comment]
>  I'm not sure if it can be in a path though. ? starts the query component

These "query components" are passed into the `REQUEST_URI` by the client. Some servers interpret that as GET parameters (as does PHP) but static web servers just don't care. Even typical dynamic web server setups will react to a `index.php?foo=bar` REQUEST_URI by looking up whether there's a file named exactly like that, otherwise pass the request to `index.php`.

So my opinion is if the web clients/servers allow it, and it is an obvious choice by the website maintainer to introduce such characters in their paths, why prevent it? It's in my opinion more confusing to users to just silently drop characters.

>  I think we need to remove all of ?, /, # from paths.

After thinking it through, i think only newlines and `/` should be removed from paths. Newlines because they cannot be spelled out in web browsers. `/` because it won't be extracted from the filesystem (it is forbidden there) and within the `slug` frontmatter it makes no sense (there is already `path` frontmatter for that).

> As for the config name, I think slugify_paths might be better since slugify is a bit too generic. (...) slugification of anchors

OK i'll use a single `slugify_paths` for all that.

**Comment by Keats** [comment]
```js
link = document.createElement('a');
link.href = "http://some-site.com/hello?/ho";
link.pathname
> "/hello"
```
Same thing happens with `#` and with both in Python `urlparse`:

```
>>> parse.urlparse("http://some-site.com/hello?/ho")
ParseResult(scheme='http', netloc='some-site.com', path='/hello', params='', query='/ho', fragment='')
>>> parse.urlparse("http://some-site.com/hello#/ho")
ParseResult(scheme='http', netloc='some-site.com', path='/hello', params='', query='', fragment='/ho')
```
To me that's evidence that they need to be removed since even browsers and all programming languages will not understand them correctly. They would be valid urls but not in the form expected by the user so it seems dangerous to me to allow them.

**Comment by chris-morgan** [comment]
For a project like this, I think it’s reasonable to hope that anyone that uses `?` and `#` knows what they’re doing, and are using the proper access techniques, which must ensure that the URLs are encoded as *necessary* (I thereby exclude the gratuitous encode-anything-but-ASCII technique), so that `?` becomes `%3f` and `#` becomes `%23`—something which must already be done for `%`, encoding it as `%25`.

Blocking `/` outright seems technically reasonable, though I could easily argue in the other direction too.

There are two main schools of slugification: the lower-kebab-case approach, *most commonly* paired with reduction to ASCII; and the Just_turn_spaces_into_underscores_and_leave_the_rest_alone approach as seen in things like Wikipedia. There is a place for each of these, and I would consider it reasonable to allow you to select slugification scheme for taxonomies and anchors.

For my part, I’m content with what I did in https://github.com/chris-morgan/zola/commit/b9fda1f84b0a361625d40f972cb9de3aae915066.

**Comment by Keats** [comment]
>  Just_turn_spaces_into_underscores_and_leave_the_rest_alone approach as seen in things like Wikipedia

I think that's what generated id/anchors are going to get.

I'm pretty happy with the state of @southerntofu PR with the detailed changes in https://github.com/getzola/zola/pull/781/files#diff-eb8d99ad43cf3761c80af5ab717d516dR10

**Comment by chris-morgan** [comment]
I expect all slugification to match the one scheme: either paths and anchors should all be lower-kebab-case, or paths and anchors should all be Just_space_changed. Changing the slugification scheme is of course a breaking change.

Maybe a config option like `slug_scheme = "lower-kebab-case"` or `"Space_to_underscore"`, defaulting to "lower-kebab-case".

**Comment by Keats** [comment]
If `slugify_path` is `true`, the slugification is the same as currently: remove all non ascii chars from paths and anchors.
If it's false, we only remove characters causing issues in URLs and on NTFS so no slugification there. I wanted to make it look like Wikipedia but I've just noticed they replaced their spaces by `_` in the URLs as well, which is where I was getting the idea to do that for anchors.
I don't want to have 2 different slugifications process so maybe just not touch anchors at all when `slugify_path` is `false`.

**Comment by southerntofu** [comment]
OK so in regards to #781 i think we still have to:
- maybe_slugify anchors
- URL encode permalinks and anchors

Am i correct?

**Comment by Keats** [comment]
I think so, unless I forgot something.

**Comment by southerntofu** [comment]
OK.

As a reminder: docs should make it clear that `path` frontmatter is not URL-encoded (it is a valid NTFS path name) but `permalink` is.

**Comment by Keats** [comment]
@southerntofu FYI I'll push that to 0.10 rather than 0.9 since it is a huge change that I want to get 100% right and deserves its own release.

**Comment by Keats** [comment]
Finally got around to trying the branch a bit more:

- spaces in filename & anchor are going to be problematic since it's not allowed in commonmark links. The user needs to escape the space manually by replacing them with `%20` but then it doesn't match what Zola has so we need to replace it by spaces before
- `()` in internal links/anchors are going to be problematic as they are supposed to be the link title in CommonMark IF there are spaces before

Both of those issues might be fine when you have a web editor like Wikipedia but not great when editing a markdown file by hand and need to sprinkle `%20` everywhere manually. I'll think about it a bit more but I'm erring towards removing spaces entirely/replacing them.

The PR itself works great @southerntofu ! I'll have a look at non slugifying anchors later this week unless you beat me to it :).

**Comment by Geobert** [comment]
That was a big thread to read. I'm french and Keats asked me to give my opinion on this :)

I'm pretty happy with what's happening to the accents right now, I don't like accents in URLs.
I also agree that we should keep user input as much as possible.
And if ever we choose to keep accent in slugification process, an option to slugify them to non-accent should be provided (but keeping things like `_` untouched)

**Comment by Keats** [comment]
> And if ever we choose to keep accent in slugification process, an option to slugify them to non-accent should be provided (but keeping things like _ untouched)

There would be an option to select it and it would be slugifying by default (eg keep current behaviour). However, most slug function (like the one WordPress uses and the one Zola uses) *will* replace _ by - and that part is not going to change imo. You can just set the slugify option to False if needed.

I got sidetracked from that issue but I'm planning to release 0.10 as soon as it is in and working. Considering the current state which is mostly editing Markdown file by hand, I am going to strip spaces in filenames/anchors to avoid the common `%20` issue. I think `( ) [ ]` also need to be removed since they will mess up the markdown. Overall users without insane page paths should still be fine and in a better spot than before.

@southerntofu are you interested in finishing it or should I take care of it?

**Comment by phil-opp** [comment]
I think it's important that URLs of existing sites don't change silently when updating Zola. I know that version 0.10 technically allows breaking changes, but risking to cause 404 errors on existing sites would be a very bad thing to do. So I agree with the proposal that we shouldn't change the default, but provide an option to disable slugification if desired. The documentation for this option could also mention the possible problems that special characters in URLs can cause for other programs, to let the user make an informed decision.

Regarding changing `_` to `-`: It doesn't matter to me personally. Please just keep the default unchanged to avoid breaking existing sites. 

Another idea: Maybe the `slugify` option should be string instead of a bool. This way, we can provide multiple options, e.g. `full` for the current behavior, `off` for keeping everything exactly as written, and `remove-non-ascii` for removing accents etc. but keeping `_` and `-`.

**Comment by Keats** [comment]
The slug option as a string has been proposed before but I don't really want to support more than on/off state or have multiple types of slugification.

**Comment by Keats** [comment]
I have an updated version of @southerntofu PR at https://github.com/getzola/zola/pull/875

It does both paths & anchors, stripping a few specific characters in each case: [paths](https://github.com/getzola/zola/pull/875/files#diff-993df5cb1315257aa466c6c8af5aa9daR13) and [anchors](https://github.com/getzola/zola/pull/875/files#diff-993df5cb1315257aa466c6c8af5aa9daR20).

In the end, I thought that stripping whitespace will make things pretty bad so I'm doing like Wikipedia and replacing them by `_` in both cases.

Any thoughts on that/anyone wanting to try it?

**Comment by chris-morgan** [comment]
I’ve just come back to this to rebase my own patch set on top of this, with what landed in #875. I find critical problems in its design and implementation, so that I genuinely can’t work with it, and so have reverted the commit wholesale in my branch, retaining my own much simpler “just stop slugifying paths” patch.

When I started writing this comment, I was describing what had landed as “catastrophically bad” in its particular design niche, and was recommending complete or almost complete reversion, but I have since decided that it is in fact redeemable, although the current state of it is very bad. I propose a rectifying course of action at the end of this comment.

For starters, I still very strongly oppose modifying the slug in the filename or metadata that the user specified in *any* way. Assume that the user wrote what they meant—this is a fairly reasonable assumption for Zola’s target market. If you really want to provide the functionality (and I *do* admit that there are some users for whom it may be desirable), let people opt *into* it changing what they said, not opt *out of* it.

Then also, I honestly see no purpose in *any* of strip_invalid_paths_chars. I genuinely have a case where I have deliberately put `/` in a slug, and I mean that to continue to work. (I’d much rather that I could actually use a subdirectory, but that’s not working without making the subdirectory a new section, which I can’t do because it’d break other things, since templates only have a list of the pages in a section, not done recursively.) Perhaps I am wresting Zola’s capabilities here, and certainly I am working around a design limitation, but it’s my workflow™ and this breaks it.

It’s not terribly common on web pages (attachments is the most common situation), but there *are* plenty of URLs out there with spaces in them. (And parentheses, well, Wikipedia demonstrates the idea.) Markdown links don’t like spaces or parentheses? Spaces, encode them with `%20` or `&#x20;`; parentheses, escape with backslash or match them, and the problem’s gone.

Seriously, if the user specifies these values, assume that they know what they’re doing—don’t make it *literally impossible* for them to use Zola.

As you have noted in the past, there may be problems with @/… resolution when you escape or encode URLs. (I’m not certain; I’ve never tried it.) But there have always been workarounds there: use a filename without special characters and only put the special characters in the `slug` metadata field; or write the likes of `[](/…/)` instead of `[](@/….md)`. Sorting it out fully so that you do extra URL encoding or decoding in certain places is something that can be done later, but it’s not good to actively prevent valid use cases just because you can’t handle them perfectly in all cases.

That’s paths. Now onto anchors.

Again, I utterly reject the purpose of strip_invalid_anchors_chars. Throw it away; spaces are fine, and the RFC 3986 limitations are entirely spurious anyway (because of URL encoding).

And then slugification. Tying anchor slugification into slugify_paths is an intrinsically incorrect design. Paths and anchors are fundamentally different: ignoring outliers, page/section slugs are already slugs (either from filenames or from the slug metadata field), but headings are *not* slugs. Further, there is much precedent for paths and anchors using different stylistic conventions, e.g. paths lower-kebab-case and slugs Underscored_original_case. Treating the two as the same is not good. Currently with zola/next, if I want my rust-cfg_attr page slug, I must disable slugify_paths, and that immediately breaks all my anchors, unslugifying them. This cannot be borne.

Here, then, is a proposal for a course of action:

1. MANDATORY: Discard strip_invalid_anchor_chars and strip_invalid_paths_chars. They’re actively wrong, and completely block Zola from being used on sites that do actually use any of those characters. Sure, there are problems with strip_invalid_paths_chars particularly, but they’re not critical and can be addressed later.

2. MANDATORY: Split slugify_paths into slugify_paths and slugify_anchors, and change anchors to using slugify_anchors.

3. NEGOTIABLE: Turn slugify_paths off by default. Also clarify the documentation which is quite unclear about the defaults and which values change its meaning. Truth to tell, I think from half of the documentation of it and its presence in the changelog as a breaking change rather than an addition that this was intended to be false by default—perhaps it got changed back to true because anchors had been tied to it?

With all of that, a sound bed is laid for future work, things like handling spaces in paths better, and allowing slugify_paths and slugify_anchors to be a string, a slugification scheme to use, rather than just a boolean.

**Comment by chris-morgan** [comment]
I forgot to mention the NTFS paths issue: I don’t think there’s value in restricting paths so they’re valid on NTFS. Most platforms don’t have those restrictions, and the web doesn’t have those restrictions at all, so it isn’t great to prevent people from doing something perfectly valid just because a platform that they’re probably not even using doesn’t support it. Again, I’m for trusting the user. Sure, the user might get bitten later on when they try to switch to Windows and their colon paths don’t work. I’m OK with that rare case.

If I were talking about Perl, I would *absolutely* want colons in my slugs sometimes, just like I used an underscore in rust-cfg_attr.

**Comment by chris-morgan** [comment]
I have implemented my proposal in #910, and I find that it does indeed please me, so I’ve replaced my earlier “just don’t slugify paths” patch with it on [my branch of zola with the patches I’m using](https://github.com/getzola/zola/compare/next...chris-morgan:next).

**Comment by Keats** [comment]
Good point for putting the path in the front-matter and not just the filenames.

The issue with `[](@/….md)` is when you're linking to an anchor, you now need to know the CommonMark spec to know what to escape. I had to check the markdown AST to know what was happening and I am guessing most people will just assume it's a bug in Zola. How does the link checker works with escaped characters? Right now I think it would just fail saying the link does not exist.

3 is not negotiable, the default should continue being to slugify. Otherwise someone could update Zola and have a new build having completely different URLs.

**Comment by Keats** [comment]
The output for a page is also to be considered. Even if someone puts a slug in the front-matter, zola might fail with some random FS error when it's time to build the site.

**Comment by Keats** [comment]
https://github.com/getzola/zola/pull/929 is another improved version allowing several strategies. This way we can have a slug mode, a "safe" mode (ie everything except characters not allowed in filesystems) and an off mode where it is keeping everything as is.

**Comment by southerntofu** [comment]
Nice work @Keats! zola > 0.10 now has i18n-friendly URLs <3

Are you also happy with these changes @chris-morgan?
