### ISSUE TITLE
Change to page front-matter won't update transparent section listing

### ISSUE THREAD

**Issue by zdenek-crha** [getzola/zola#789]
# Bug Report

## Environment

Zola version: 0.8.0

## Site setup

* index section listing page titles
* transparent sub-section listing page titles
* single page with title in transparent sub-section

[transparent_section_pages_not_updated.zip](https://github.com/getzola/zola/files/3556360/transparent_section_pages_not_updated.zip)

## Step to reproduce

* start `zola serve`
* open site in browser with live-reload enabled
  * open new tab with index section
  * open new tab with transparent sub section
  * open new tab with page
* update title in page front-matter and save

## Expected Behavior

After live-reload or manual reload, all three tabs show **new** page title (in section listings and in page).

## Current Behavior

The transparent section listing displays **old** page title. Index listing and page itself display **new** page title.

## Workaround

Start and stop `zola serve` and refresh.

**Comment by Keats** [comment]
Looks like the rebuild is only re-rendering the page/section that changed since this was written before the existence of `transparent`. A bit annoying to fix since it affects both section and pages rebuild but it isn't hard. If parent of page/section has transparent=true, re-render it and go up the ancestry until it's not the case anymore. No need to re-render pages of sections, only the section itself.
A test in the rebuild subcrate would be great!
