### ISSUE TITLE
Windows release should be .zip

### ISSUE THREAD

**Issue by ralfbiedert** [getzola/zola#808]
# Bug Report

## Environment

Zola version: 0.9

## Expected Behavior
The released binary for Windows should ship in a `.zip` file, not a `.tar.gz`, as Windows doesn't have an easy way to unpack these. 

Just encountered this when trying out 0.9, now I'm side tracked to find an app that can extract the archive ...

**Comment by Keats** [comment]
Yeah and it probably broke the Windows package managers :(

It's because there is a new CI build pipeline (https://github.com/getzola/zola/blob/master/azure-pipelines.yml) which should have a zip stage on Windows rather than https://github.com/getzola/zola/blob/master/azure-pipelines.yml#L118-L120 which I seem to have forgotten to swap.

I'm in a spot with bad internet this week, if anyone has the bandwidth to fix it and do a PR on master I'll appreciate it. I'll overwrite the releases afterwards.

**Comment by Keats** [comment]
Ok I did the fix and force pushed the tag, we'll see how it behaves..

**Comment by Keats** [comment]
That's fixed
