### ISSUE TITLE
Install via brew checksum mismatch error

### ISSUE THREAD

**Issue by jamiebarnett** [getzola/zola#823]
# Bug Report

## Environment

Ubuntu 18.04.3 LTS on a Digital Ocean droplet

Zola version:

https://github.com/getzola/zola/archive/v0.9.0.tar.gz

## Expected Behavior

zola should have been installed

## Current Behavior

zola does not install and I get the following error

```
$ brew install zola
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing dependencies for zola: cmake
==> Installing zola dependency: cmake
==> Downloading https://linuxbrew.bintray.com/bottles/cmake-3.15.4.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/fb/fbcd772374a67e228524bc32a647a0922916ef2a1baf09d3c7e6883
######################################################################## 100.0%
==> Pouring cmake-3.15.4.x86_64_linux.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /home/linuxbrew/.linuxbrew/share/emacs/site-lisp/cmake
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.15.4: 5,803 files, 58.2MB
==> Installing zola
==> Downloading https://github.com/getzola/zola/archive/v0.9.0.tar.gz
==> Downloading from https://codeload.github.com/getzola/zola/tar.gz/v0.9.0
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: a5b7658c9c56bd53613cd40254536ccdd6937444b935458c45416b8fb78bbcad
  Actual: 8d226ec764f2bc06de8e49e2e22ccf37811bc478bbcaa83c2c841b222ef4fc4e
 Archive: /home/jamie/.cache/Homebrew/downloads/36ef2d187aa67e758c553ab68c16951a450e9caf494c7c9aa6377cbe62567ab2--zola-0.9.0.tar.gz
To retry an incomplete download, remove the file above.

```

## Step to reproduce
```
# install linux brew
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

# install deps
$ sudo apt-get install build-essential curl

# install rust
$ brew install rust

# install zola
$ brew install zola
```

**Comment by Keats** [comment]
There were some issues with the new CI pipeline for the 0.9.0 release which required rebuilding it a couple of times. I guess the maintainer in Homebrew used one of the previous versions :/
I don't know who the maintainers are or where the Homebrew repos for apps are though :(

**Comment by jamiebarnett** [comment]
@Keats Thanks for your quick reply. Are there any alternative installation options for Ubuntu other than building from source?

**Comment by Keats** [comment]
It should be available via `snap` but I haven't tried it personally. You can also download the linux binary from the releases page and `mv` it into Ubuntu binary folder manually.

**Comment by samford** [comment]
I created a pull request in the homebrew-core repo (Homebrew/homebrew-core#45819) to update the sha256 checksum, so this should be resolved if/when it's merged.  I also created a PR (Homebrew/homebrew-core#45839) to fix building from source via `brew --build-from-source`, since it's currently broken due to not using the `--locked` flag with `cargo install`.

Regarding maintainers, if you look at [pull requests that update the Zola formula to the latest version](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+zola+is%3Aclosed), it's done by different people who presumably use both Homebrew and Zola (myself included) and there doesn't appear to be anyone in particular who takes care of it.  It's basically whoever gets to it first.

The checksum is calculated when the formula is updated for a new version release and doesn't change unless it's manually updated through a pull request.  The formula was updated pretty quickly after the 0.9.0 release, so the later 0.9.0 build(s) must have come afterward.

This may be something to be mindful of going forward.  It would be ideal to avoid modifications to archives after release but if this does happen again in the future, it might be good to open a Zola issue (once no further changes will be made) like "Update Homebrew checksum for 0.9.0".  This way, people like me who try to keep the Homebrew formula up to date can take notice and handle the checksum change.

One thing to note is that the Homebrew maintainers seem to like for there to be an explanation behind the change in checksum (to help rule out the chance that someone, for example, gained access to a privileged user account and made malicious changes to the build), so it would also be good to explain why the checksum changed in the issue.  I referenced the above explanation from @Keats in the current PR, so hopefully that should be enough this time around.

**Comment by Keats** [comment]
Yeah the changing checksums was my fault, I had some errors on the Windows side of the CI and the action was rebuilding all platforms. Going forward there will only one single checksum as expected and was was the case before, this was a one-time occurrence after switching to Azure Pipelines.

Thanks for the PRs @samford !

**Comment by zbeekman** [comment]
> There were some issues with the new CI pipeline for the 0.9.0 release which required rebuilding it a couple of times.

FYI, it is best practice to yank botched releases and bump the patch version. People suspect supply chain attacks and other strange stuff when you release a package, then change it and keep the same tag/version number.

**Comment by samford** [comment]
My PR to address these issues (Homebrew/homebrew-core#45839) has now been merged, so the SHA256 mismatch issue is fixed and you should also be able to successfully build from source (due to the addition of the `--locked` flag to the `cargo install` command).

**Comment by jamiebarnett** [comment]
can confirm I am now able to install zola, thanks for investigating/ fixing!
